/* C code generated by Lisaac compiler (www.lisaac.org) */

#define _LARGE_FILE_API
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
int print_string(char *str);
int arg_count;
char **arg_vector;

/*==========================*/
/* EXTERNAL                 */
/*==========================*/

/* UINTEGER_64 */
#include <stdint.h>
/* FLOAT_REAL */
#include <math.h>
/* STRING */

#include <errno.h>
#include <string.h>  
  
/* BUILD_LISAAC */
#include <unistd.h>
/* FILE_UTILS */

#undef  __wur
#define __wur
#include <unistd.h>

/* COMMAND_ARGS */

#include <unistd.h>

#if defined(_WIN32)
  #include <windows.h>
#elif defined(__APPLE__)
  #include <mach-o/dyld.h>
#elif defined(__linux__)
  #include <unistd.h>
#endif

void get_executable_path(char *buf, int64_t size) {
#if defined(_WIN32)
    int len = GetModuleFileNameA(NULL, (char*)buf, size - 1);
    buf[len] = '\0';
#elif defined(__APPLE__)
    uint32_t s = size;
    _NSGetExecutablePath((char*)buf, &s);
#elif defined(__linux__)
    int len = readlink("/proc/self/exe", (char*)buf, size - 1);
    buf[len] = '\0';
#endif
}
  
/* SYSTEM */

char *system_name()
{ char *n; 
#if defined(_WIN32)
n = "windows";
#elif defined(__ANDROID__)
n = "android";
#elif defined(__APPLE__)
n = "apple";
#else 
n = "unix";
#endif
return n;
}
/* ENVIRONMENT */

#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>

#ifdef _WIN32
#define WEXITSTATUS(status) (status)
#else
#include <sys/wait.h>
#endif

#ifdef _WIN32
    #include <process.h>   // pour _spawnl
    #include <windows.h>
#endif

/******************* Run background *************************/

int run_background(const char *cmd) {
#ifdef _WIN32
    // Version Windows : _spawnl passe par cmd.exe /C "cmd"
    return _spawnl(_P_NOWAIT, "C:\\Windows\\System32\\cmd.exe",
                   "cmd.exe", "/C", cmd, NULL);
#else
    // Version POSIX : fork + execlp "sh -c cmd"
    pid_t pid = fork();
    if (pid == 0) {
        execlp("sh", "sh", "-c", cmd, (char*)NULL);
        exit(1);
    }
    else if (pid < 0) {
        return -1;
    }
    return pid; // le parent continue immédiatement
#endif
}

/* SYSTEM_IO */

#if defined(ARDUINO)

#elif(__ANDROID__)

#include <stdio.h>
#include <stdlib.h>

#include <android/asset_manager.h>
//#include <androidfw/Asset.h>
//#include <androidfw/AssetDir.h>
//#include <androidfw/AssetManager.h>
//const char* AAssetDir_getFileName(AAssetDir* assetDir, int index);
/*struct AAssetDir {
    AssetDir* mAssetDir;
    size_t mCurFileIndex;
    String8 mCachedFileName;
    AAssetDir(AssetDir* dir) : mAssetDir(dir), mCurFileIndex(0) { }
    ~AAssetDir() { delete mAssetDir; }
};*/

/* Hardware 'print_char' */
void print_char(char);

char output[256];
int output_idx;

/* Hardware 'exit' */
void die_with_code(long);

#else // Windows, Unix, MacOS
  
#include <stdio.h>
#include <stdlib.h>

/* Hardware 'print_char' */
void print_char(char);

/* Hardware 'exit' */
void die_with_code(int64_t);

#endif

/* ALIAS__TO */

#ifndef H_TABLE
unsigned int hash_table[]={
193,389,769,1543,3079,6151,12289,24593,49157,98317,196613,393241,
786433,1572869,3145739,6291469,12582917,25165843,50331653,100663319,
201326611,402653189,805306457,1610612741};
#define H_TABLE
#endif


/*==========================*/
/* TYPE                     */
/*==========================*/

/* Generic Object */
struct ___OBJ {
  uint32_t __id;
};

typedef struct li__FC_struct __li__FC;
typedef struct li__FB_struct __li__FB;
typedef struct li__ZDB_struct __li__ZDB;
typedef struct li__GB_struct __li__GB;
typedef struct li__2B_struct __li__2B;
typedef struct li__TH_struct __li__TH;
typedef struct li__3VE_struct __li__3VE;
typedef struct li__1B_struct __li__1B;
typedef struct li__PB_struct __li__PB;
/* NULL */
#ifndef NULL
#define NULL ((void *)0)
#endif

typedef int64_t __li__K;
typedef char __li__MB;
/* li__GB */
#define __li__GB__ 0
struct li__GB_struct {
  __li__K li__BC;
  __li__MB *li__CC;
};
/* li__FC */
#define __li__FC__ 0
struct li__FC_struct {
  int __id;
  __li__GB li__GC;
  __li__K li__12;
};
/* li__FB */
#define __li__FB__ 1
struct li__FB_struct {
  int __id;
  __li__GB li__LB;
  __li__K li__GXE;
};
/* li__ZDB */
#define __li__ZDB__ 1
struct li__ZDB_struct {
  __li__K li__IQB;
  __li__K li__KQB;
  void **li__HRB;
};
typedef char __li__C;
typedef void * __li__RB;
typedef uintptr_t __li__C1C;
__li__C1C li__C1C_;
#define li__C1C__ (&li__C1C_)
#define __li__C1C__ 2

/* li__2B */
#define __li__2B__ 3
struct li__2B_struct {
  __li__FC *li__KC;
  __li__C li__WC;
};
/* li__TH */
#define __li__TH__ 4
struct li__TH_struct {
  __li__K li__LUB;
  __li__K li__DCC;
  __li__FB **li__PCC;
};
/* li__3VE */
#define __li__3VE__ 5
struct li__3VE_struct {
  __li__FB *li__DXE;
  __li__3VE *li__0XE;
};
#define li__B__ 1
#define li__I__ 0
/* li__1B */
#define __li__1B__ 6
struct li__1B_struct {
  __li__FB *li__UD;
  __li__FB *li__BF;
  __li__FB *li__JF;
  __li__FB *li__5I;
  __li__FB *li__HN;
  __li__FB *li__0N;
  __li__FB *li__3P;
};
typedef signed char __li__X1C;
/* li__PB */
#define __li__PB__ 7
struct li__PB_struct {
  void *self;
};
typedef int64_t __li__11C;

void *table_type[8];

/*==========================*/
/* GLOBAL                   */
/*==========================*/

__li__GB li__GB_;
#define li__GB__ (&li__GB_)

__li__FC li__FC_={__li__FC__};
#define li__FC__ (&li__FC_)

__li__FB li__FB_={__li__FB__};
#define li__FB__ (&li__FB_)

__li__ZDB li__ZDB_;
#define li__ZDB__ (&li__ZDB_)

__li__2B li__2B_;
#define li__2B__ (&li__2B_)

__li__TH li__TH_;
#define li__TH__ (&li__TH_)

__li__3VE li__3VE_;
#define li__3VE__ (&li__3VE_)

__li__1B li__1B_;
#define li__1B__ (&li__1B_)

__li__PB li__PB_;
#define li__PB__ (&li__PB_)

__li__C1C li__Z2C;
__li__C1C li__22C;
__li__K li__CWE;
__li__K li__T0F;
void **li__UWE;
__li__K li__30F;
__li__TH *li__0H;
__li__ZDB li__AEB;
__li__FC *li__DDB;

/*==========================*/
/* STRING ALIAS             */
/*==========================*/

__li__FB __string_1={__li__FB__,{39,"Installing Lisaac Ω Compiler and Tools."},1039603244};
__li__FB __string_2={__li__FB__,{8,"--verbose"},4310945};
__li__FB __string_3={__li__FB__,{14,"Unknow option \""},395385922};
__li__FB __string_4={__li__FB__,{1,"\"."},182};
__li__FB __string_5={__li__FB__,{30,"Usage: build_lisaac [--verbose]"},1169628897};
__li__FB __string_6={__li__FB__,{13,"Running from \""},1636822322};
__li__FB __string_7={__li__FB__,{6,"windows"},631871};
__li__FB __string_8={__li__FB__,{6,"android"},545144};
__li__FB __string_9={__li__FB__,{4,"apple"},34325};
__li__FB __string_10={__li__FB__,{3,"unix"},9788};
__li__FB __string_11={__li__FB__,{29,"Warning: strange system name \""},717519666};
__li__FB __string_12={__li__FB__,{2,"\".\n"},738};
__li__FB __string_13={__li__FB__,{7,"system=\""},2535718};
__li__FB __string_14={__li__FB__,{53,"Warning: Warning: Avoid spaces in the L\
isaac Ω path.\n"},2023170514};
__li__FB __string_15={__li__FB__,{11,"lisaac_dir=\""},601715318};
__li__FB __string_16={__li__FB__,{6,"lisaac/"},587531};
__li__FB __string_17={__li__FB__,{45,"buid_lisaac must be run from lisaac dir\
ectory."},1730897853};
__li__FB __string_18={__li__FB__,{2,"bin"},2098};
__li__FB __string_19={__li__FB__,{15,"lisaac_bin_dir=\""},1567695478};
__li__FB __string_20={__li__FB__,{3,"elix"},8732};
__li__FB __string_21={__li__FB__,{9,"elix_dir=\""},35897974};
__li__FB __string_22={__li__FB__,{3,"HOME"},6249};
__li__FB __string_23={__li__FB__,{26,"Warning: No $HOME variable."},1202161154};
__li__FB __string_24={__li__FB__,{13,"user_homedir=\""},1768467062};
__li__FB __string_25={__li__FB__,{8,".elix.cfg"},5255087};
__li__FB __string_26={__li__FB__,{11,"Remove old \""},488104162};
__li__FB __string_27={__li__FB__,{14,"Cannot remove \""},1183127410};
__li__FB __string_28={__li__FB__,{4,"SHELL"},27340};
__li__FB __string_29={__li__FB__,{18,"No $SHELL variable."},769099266};
__li__FB __string_30={__li__FB__,{12,"/usr/bin/bash"},1434982340};
__li__FB __string_31={__li__FB__,{8,"/bin/bash"},5248964};
__li__FB __string_32={__li__FB__,{6,"shell=\""},612310};
__li__FB __string_33={__li__FB__,{42,"C compiling lisaac/bin/lisaac.c ... wai\
t..."},1101908318};
__li__FB __string_34={__li__FB__,{25,"gcc lisaac.c -o lisaac -O2"},2097005374};
__li__FB __string_35={__li__FB__,{6,".bashrc"},323179};
__li__FB __string_36={__li__FB__,{7,"/bin/zsh"},1312660};
__li__FB __string_37={__li__FB__,{5,".zshrc"},87915};
__li__FB __string_38={__li__FB__,{5,".cshrc"},82027};
__li__FB __string_39={__li__FB__,{10,"No rc_file."},115389634};
__li__FB __string_40={__li__FB__,{29,"Update lisaac/make.lip config."},1969519578};
__li__FB __string_41={__li__FB__,{7,"make.lip"},2323796};
__li__FB __string_42={__li__FB__,{20,"Cannot read make.lip."},1284363646};
__li__FB __string_43={__li__FB__,{19,"+ target:STRING := \""},225079026};
__li__FB __string_44={__li__FB__,{34,"Update lisaac/elix/assets/elix.cfg."},208096210};
__li__FB __string_45={__li__FB__,{5,"assets"},138323};
__li__FB __string_46={__li__FB__,{7,"elix.cfg"},2240431};
__li__FB __string_47={__li__FB__,{39,"Cannot read lisaac/elix/assets/elix.cfg\
."},1392712112};
__li__FB __string_48={__li__FB__,{13,"shortcut   : \""},1496853570};
__li__FB __string_49={__li__FB__,{7,"standard"},2495292};
__li__FB __string_50={__li__FB__,{5,"mac_os"},144863};
__li__FB __string_51={__li__FB__,{12,"decorated  : "},96437000};
__li__FB __string_52={__li__FB__,{4,"false"},34609};
__li__FB __string_53={__li__FB__,{3,"true"},9817};
__li__FB __string_54={__li__FB__,{-1,""},0};
__li__FB __string_55={__li__FB__,{32,"Update lisaac/misc/new_assets.sh."},1925998462};
__li__FB __string_56={__li__FB__,{3,"misc"},9215};
__li__FB __string_57={__li__FB__,{12,"new_assets.sh"},280173012};
__li__FB __string_58={__li__FB__,{44,"Cannot read lisaac/elix/assets/new_asse\
ts.sh."},1392712141};
__li__FB __string_59={__li__FB__,{1,"#!"},173};
__li__FB __string_60={__li__FB__,{37,"lisaac/misc/new_assets.sh not updated."},434446708};
__li__FB __string_61={__li__FB__,{32,"Compiling lisaac/elix ... wait..."},668433862};
__li__FB __string_62={__li__FB__,{20,"lisaac elix -q -boost"},1653373680};
__li__FB __string_63={__li__FB__,{46,"Compiling lisaac/example/welcome.li ...\
 wait..."},1437157202};
__li__FB __string_64={__li__FB__,{6,"example"},570709};
__li__FB __string_65={__li__FB__,{6,"welcome"},627145};
__li__FB __string_66={__li__FB__,{14,"elix welcome.li"},191133497};
__li__FB __string_67={__li__FB__,{23,"lisaac welcome -q -boost"},492600048};
__li__FB __string_68={__li__FB__,{22,"example/welcome/welcome"},1373524425};
__li__FB __string_69={__li__FB__,{35,"Installation Completed Successfully."},568466528};
__li__FB __string_70={__li__FB__,{26,"Open a new terminal window."},673293306};
__li__FB __string_71={__li__FB__,{2,"or:"},2290};
__li__FB __string_72={__li__FB__,{8,"source ~/"},9984103};
__li__FB __string_73={__li__FB__,{37,"Rerun using --verbose to try to debug."},843204820};
__li__FB __string_74={__li__FB__,{3,"cd \""},8098};
__li__FB __string_75={__li__FB__,{0,"\""},34};
__li__FB __string_76={__li__FB__,{4,"Fail."},26286};
__li__FB __string_77={__li__FB__,{11,"exit status:"},585729878};
__li__FB __string_78={__li__FB__,{14,"Create/Update \""},2120307954};
__li__FB __string_79={__li__FB__,{25,"Checking export PATH for \""},1318816130};
__li__FB __string_80={__li__FB__,{9,"Creating \""},27241362};
__li__FB __string_81={__li__FB__,{12,"export PATH=\""},206478230};
__li__FB __string_82={__li__FB__,{6,"$PATH\"\n"},252690};
__li__FB __string_83={__li__FB__,{31,"\n# **** LISAAC-OMEGA TOOLS ****\n"},2078533586};
__li__FB __string_84={__li__FB__,{12,"Cannot read \""},1684556834};
__li__FB __string_85={__li__FB__,{4,"Tag \""},29522};
__li__FB __string_86={__li__FB__,{8,"\" not in "},3350632};
__li__FB __string_87={__li__FB__,{0,"."},46};
__li__FB __string_88={__li__FB__,{11,"Open write \""},483640562};
__li__FB __string_89={__li__FB__,{19,"-9223372036854775808"},240231608};
__li__FB __string_90={__li__FB__,{6,"writen "},640552};
__li__FB __string_91={__li__FB__,{6," bytes."},271946};
__li__FB __string_92={__li__FB__,{6,"Close \""},422578};
__li__FB __string_93={__li__FB__,{29,"Crash ALIAS TO : hash code < 0"},693219696};
__li__FB __string_94={__li__FB__,{1,"/\\"},280};
__li__FB __string_95={__li__FB__,{0,":"},58};

/*==========================*/
/* FUNCTION HEADER          */
/*==========================*/

/* Source code */
void die_with_code(__li__K li__SDD);
void print_char(__li__MB li__XCD);
void bug_compilo_042();
static __li__FC* li__GJB(__li__K li__IJB);
static __li__FB** li__CRJ(__li__K li__ERJ);
static void li__DOE(__li__FC *li__EOE,__li__MB *li__FOE);
static __li__FB* li__12D(__li__FC *li__22D);
static void li__41(__li__FB *li__51);
static void li__3F(__li__FC *li__5F);
static void li__M4D(__li__FC *li__N4D,__li__FB *li__O4D);
static void li__45D(__li__FC *li__55D,void *li__AAE);
static __li__FC* li__2GE(__li__FC *li__3GE,void *li__4GE);
static void li__MMI(__li__FC *li__NMI);
static __li__FC* li__MPB();
static void li__EQB(__li__ZDB *li__FQB,__li__FC *li__GQB);
static __li__C li__QK(__li__FB *li__RK,__li__MB li__SK);
static void li__VNB(void *li__XNB);
static void li__YBB(__li__FB *li__0BB);
static __li__FB* li__VCB(void *li__XCB);
static void li__EJN(__li__FC *li__FJN);
static __li__MB* li__BCE(__li__FC *li__CCE);
static __li__RB li__ADC(void *li__CDC);
static void li__0LC(__li__FC *li__2LC);
static __li__K li__3XC(__li__FC *li__5XC);
static void li__3XB(__li__FB *li__5XB);
static void li__VOD(__li__FB *li__XOD);
static __li__C li__DYC(void *li__FYC,__li__FC *li__GYC);
static __li__K li__01B(void *li__21B,__li__FC *li__31B,__li__FB *li__41B);
static void li__0ZP(__li__FC *li__1ZP,__li__K li__2ZP,__li__K li__3ZP);
static void li__XBP(__li__FC *li__YBP,__li__FB *li__ZBP,__li__K li__0BP);
static void li__B3B(__li__FB *li__D3B,__li__FC *li__E3B);
static void li__0DP(__li__FC *li__1DP,__li__FC *li__2DP,__li__K li__3DP);
static __li__K li__KZC(__li__FC *li__MZC);
static void li__UAC(__li__FC *li__VAC,__li__K li__WAC);
static __li__MB* li__HHG(__li__K li__JHG);
static void li__IWG(__li__MB *li__JWG,__li__K li__KWG,__li__K li__LWG);
static __li__FB* li__LZF(__li__FC *li__MZF);
static void li__K0F(__li__FB *li__M0F);
static __li__K li__JPG(__li__K li__KPG);
static void li__DEE(__li__FC *li__EEE,__li__MB li__FEE);
static void li__UZE(__li__MB *li__VZE,__li__MB *li__WZE,__li__K li__XZE,__li__K li__YZE);
static void li__GVF(__li__MB *li__HVF,__li__MB *li__IVF,__li__K li__JVF);
static __li__K li__CHD(__li__FC *li__EHD,__li__C li__FHD);
static void li__PQF(__li__K li__QQF);
static __li__C li__RFC(void *li__TFC);
static void li__IRC(__li__FC *li__KRC,__li__FB *li__LRC);
static __li__K li__XTP(__li__FC *li__YTP,void *li__ZTP);
static void li__KHP(__li__FC *li__LHP,__li__FC *li__MHP);
static void li__5PP(__li__FC *li__AQP,__li__K li__BQP);
static void li__2CR(__li__MB *li__3CR,__li__K li__4CR,__li__K li__5CR,__li__K li__ADR);
static __li__K li__SWH(__li__FB *li__TWH);
static void li__YZJ(__li__K li__ZZJ);
static void init_string_alias();

/*==========================*/
/* SOURCE CODE              */
/*==========================*/

int main(int argc,char **argv)
{
   __li__FC *li__ZAD,*li__AD,*li__IK,*li__1GX,*li__4GX,*li__HGP;
  __li__RB li__JME;
  __li__C1C li__0ME;
  __li__FB *li__GLB,*li__GK,*li__VE,*li__RQ;
  __li__GB *li__ZFX,*li__0FX,*li__1FX,*li__2FX;
  __li__K li__XKB,li__GED,li__OZI,li__QZI,li__QUL,li__C1M;
  __li__TH *li__IME,*li__5BC,*li__KYI,*li__30I;
  __li__TH *li__VNE;
  __li__FB **li__OCC,**li__GZI,**li__VTL;
  __li__C li__0YI,li__MBP,li__IM;
  __li__FB **li__YJM;
  __li__MB *li__Q4;
  __li__MB li__DM;
 arg_count  = argc;
  arg_vector = argv;
;
  {
    ((__li__GB *)li__GB__)->li__BC=(__li__K)(- 1);
    li__FB__->li__LB=(*li__GB__);
    ((__li__FC *)li__FC__)->li__GC=(*li__GB__);
    li__Z2C=((__li__C1C )0);
    li__22C=((__li__C1C )0);
    li__ZAD=li__GJB(2048);
    ((__li__2B *)li__2B__)->li__KC=li__ZAD;
    ((__li__TH *)li__TH__)->li__LUB=(__li__K)(- 1);
    li__ZAD=li__GJB(512);
    init_string_alias();
    li__FB__->li__GXE=0;
    li__XKB=((__li__K )(arg_count));
    li__IME=(__li__TH *)NULL;
    li__JME=((__li__RB )(NULL));
    li__0ME=((__li__C1C )sizeof(__li__TH));
    if (0 == li__0ME) {
      li__IME=(__li__TH *)li__TH__;
    } else /* FALSE */ {
      li__JME=((__li__RB )(malloc(((li__0ME) + 3) & ~3)));
      li__Z2C=(__li__C1C)(li__Z2C - (__li__C1C)(((__li__C1C )0) - li__0ME));
      li__22C=(__li__C1C)(li__22C - (__li__C1C)(((__li__C1C )0) - li__0ME));
      li__VNE=((__li__TH *)li__JME);
      li__IME=li__VNE;
      *(li__VNE) = *(li__TH__);
    };
    li__5BC=((__li__TH *)li__IME);
    if (li__5BC->li__DCC < li__XKB) {
      li__OCC=li__CRJ(li__XKB);
      li__5BC->li__PCC=li__OCC;
      li__5BC->li__DCC=li__XKB;
    };
    li__5BC->li__LUB=(__li__K)(- 1);
    li__5BC=li__IME;
    li__XKB=0;
    li__GED=(__li__K)(((__li__K )(arg_count)) - 1);
    while ((li__XKB <= li__GED)) {
      li__DOE(((__li__FC *)li__ZAD),((__li__MB *)(arg_vector[(li__XKB)])));
      li__GLB=li__12D(((__li__FC *)li__ZAD));
      li__KYI=((__li__TH *)li__5BC);
      if ((__li__K)(li__KYI->li__LUB + 1) < li__KYI->li__DCC) {
        li__KYI->li__LUB=(__li__K)(li__KYI->li__LUB + 1);
        li__0YI=li__B__;
      } else /* FALSE */ {
        li__0YI=li__I__;
      };
      if (! li__0YI) {
        if (0 == li__KYI->li__DCC) {
          li__GZI=li__CRJ(2);
          li__KYI->li__PCC=li__GZI;
          li__KYI->li__DCC=2;
          li__KYI->li__LUB=0;
        } else /* FALSE */ {
          li__OZI=(__li__K)(li__KYI->li__DCC << 1);
          li__GZI=li__KYI->li__PCC;
          li__QZI=li__KYI->li__DCC;
          li__VTL=((__li__FB **)li__GZI);
          li__YJM=((__li__FB **)((__li__RB )(realloc((((__li__RB )li__VTL)),((__li__K)(li__OZI * ((__li__K )(sizeof(void *)))))))));
          li__QUL=(__li__K)(li__OZI - 1);
          li__C1M=li__QZI;
          while ((li__C1M <= li__QUL)) {
            li__YJM[li__C1M]=NULL;
            li__C1M=(__li__K)(li__C1M + 1);
          };
          li__KYI->li__PCC=li__YJM;
          li__KYI->li__DCC=li__OZI;
          li__KYI->li__LUB=(__li__K)(li__KYI->li__LUB + 1);
        };
      };
      ((__li__FB **)li__KYI->li__PCC)[li__KYI->li__LUB]=li__GLB;
      li__XKB=(__li__K)(li__XKB + 1);
    };
    li__0H=li__IME;
    ((__li__2B *)li__2B__)->li__WC=li__I__;
    ((__li__ZDB *)li__ZDB__)->li__IQB=(__li__K)(- 1);
    li__AEB=(*li__ZDB__);
    li__ZAD=li__GJB(1024);
    li__DDB=li__ZAD;
    ;
  };
  li__41((&__string_1));
  print_char('\n');
  li__3F(((__li__2B *)li__2B__)->li__KC);
  li__0YI=li__I__;
  li__XKB=1;
  while ((li__XKB <= li__0H->li__LUB)) {
    li__KYI=((__li__TH *)li__0H);
    if ((void *)(&__string_2) == (void *)((__li__FB **)li__KYI->li__PCC)[li__XKB]) {
      li__0YI=li__B__;
      li__30I=((__li__TH *)li__0H);
      li__GZI=li__30I->li__PCC;
      li__OZI=li__30I->li__LUB;
      li__VTL=((__li__FB **)li__GZI);
      li__QZI=li__XKB;
      while ((li__QZI != li__OZI)) {
        li__VTL[li__QZI]=li__VTL[(__li__K)(li__QZI + 1)];
        li__QZI=(__li__K)(li__QZI + 1);
      };
      li__30I->li__LUB=(__li__K)(li__30I->li__LUB - 1);
      li__XKB=li__0H->li__LUB;
    };
    li__XKB=(__li__K)(li__XKB + 1);
  };
  ((__li__2B *)li__2B__)->li__WC=li__0YI;
  li__XKB=(__li__K)(((__li__TH *)li__0H)->li__LUB + 1);
  if (li__XKB != 1) {
    li__GLB=(__li__FB *)NULL;
    li__MBP=(1 <= ((__li__TH *)li__0H)->li__LUB);
    if (li__MBP) {
      li__KYI=((__li__TH *)li__0H);
      li__GLB=((__li__FB **)li__KYI->li__PCC)[1];
    };
    li__ZAD=li__GJB((__li__K)((__li__K)((&__string_3)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__GLB)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__ZAD),(&__string_3));
    li__45D(((__li__FC *)li__ZAD),li__GLB);
    li__AD=li__2GE(((__li__FC *)li__ZAD),(&__string_4));
    li__MMI(((__li__FC *)li__AD));
    li__41((&__string_5));
    print_char('\n');
    exit((1));
  };
  if (((__li__2B *)li__2B__)->li__WC) {
    li__ZAD=((__li__2B *)li__2B__)->li__KC;
    li__AD=li__GJB((__li__K)((__li__K)((&__string_6)->li__LB.li__BC + 1) + (__li__K)(((__li__FC *)li__ZAD)->li__GC.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_6));
    li__45D(((__li__FC *)li__AD),li__ZAD);
    li__ZAD=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__ZAD));
  };
  li__Q4=((__li__MB *)(system_name()));
  li__ZAD=li__MPB();
  li__DOE(((__li__FC *)li__ZAD),li__Q4);
  li__GLB=li__12D(((__li__FC *)li__ZAD));
  li__EQB(&(li__AEB),li__ZAD);
  ((__li__1B *)li__1B__)->li__5I=li__GLB;
  if ((void *)li__GLB != (void *)(&__string_7)) {
    li__MBP=((void *)li__GLB != (void *)(&__string_8));
  } else /* FALSE */ {
    li__MBP=li__I__;
  };
  if (li__MBP) {
    li__MBP=((void *)li__GLB != (void *)(&__string_9));
  } else /* FALSE */ {
    li__MBP=li__I__;
  };
  if (li__MBP) {
    li__MBP=((void *)li__GLB != (void *)(&__string_10));
  } else /* FALSE */ {
    li__MBP=li__I__;
  };
  if (li__MBP) {
    li__41((&__string_11));
    li__41(((__li__FB *)li__GLB));
    li__41((&__string_12));
  };
  if (((__li__2B *)li__2B__)->li__WC) {
    li__GK=((__li__1B *)li__1B__)->li__5I;
    li__AD=li__GJB((__li__K)((__li__K)((&__string_13)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__GK)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_13));
    li__45D(((__li__FC *)li__AD),li__GK);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__IK));
  };
  li__GLB=li__12D(((__li__FC *)((__li__2B *)li__2B__)->li__KC));
  ((__li__1B *)li__1B__)->li__UD=li__GLB;
  li__0YI=li__QK(((__li__FB *)li__GLB),' ');
  if (li__0YI) {
    li__41((&__string_14));
    li__GK=((__li__1B *)li__1B__)->li__UD;
    li__41((&__string_15));
    li__41(((__li__FB *)li__GK));
    li__41((&__string_12));
  };
  li__GLB=((__li__1B *)li__1B__)->li__UD;
  li__GK=((__li__FB *)li__GLB);
  li__0YI=li__I__;
  li__XKB=0;
  li__GED=0;
  if ((&__string_16)->li__LB.li__BC <= li__GK->li__LB.li__BC) {
    li__XKB=(__li__K)(li__GK->li__LB.li__BC - (&__string_16)->li__LB.li__BC);
    li__GED=0;
    li__ZFX=&(li__GK->li__LB);
    li__0FX=&((&__string_16)->li__LB);
    li__1FX=&(li__GK->li__LB);
    li__2FX=&((&__string_16)->li__LB);
    li__5GF:
    {
      if ((li__XKB > li__ZFX->li__BC) || (li__GED > li__0FX->li__BC)) {
        li__IM=li__B__;
      } else /* FALSE */ {
        li__DM=((__li__MB *)li__1FX->li__CC)[li__XKB];
        li__IM=(li__DM != ((__li__MB *)li__2FX->li__CC)[li__GED]);
      };
      if (! li__IM) {
        li__XKB=(__li__K)(li__XKB + 1);
        li__GED=(__li__K)(li__GED + 1);
        goto li__5GF;
      };
    };
    li__0YI=(li__XKB > li__GK->li__LB.li__BC);
  };
  if (! li__0YI) {
    li__VNB((&__string_17));
  };
  if (((__li__2B *)li__2B__)->li__WC) {
    li__VE=((__li__1B *)li__1B__)->li__UD;
    li__AD=li__GJB((__li__K)((__li__K)((&__string_15)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__VE)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_15));
    li__45D(((__li__FC *)li__AD),li__VE);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__IK));
  };
  li__YBB(((__li__1B *)li__1B__)->li__UD);
  li__YBB((&__string_18));
  li__GLB=li__12D(((__li__FC *)((__li__2B *)li__2B__)->li__KC));
  ((__li__1B *)li__1B__)->li__HN=li__GLB;
  if (((__li__2B *)li__2B__)->li__WC) {
    li__AD=li__GJB((__li__K)((__li__K)((&__string_19)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__GLB)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_19));
    li__45D(((__li__FC *)li__AD),li__GLB);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__IK));
  };
  li__YBB(((__li__1B *)li__1B__)->li__UD);
  li__YBB((&__string_20));
  li__GLB=li__12D(((__li__FC *)((__li__2B *)li__2B__)->li__KC));
  ((__li__1B *)li__1B__)->li__0N=li__GLB;
  if (((__li__2B *)li__2B__)->li__WC) {
    li__AD=li__GJB((__li__K)((__li__K)((&__string_21)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__GLB)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_21));
    li__45D(((__li__FC *)li__AD),li__GLB);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__IK));
  };
  li__GLB=li__VCB((&__string_22));
  ((__li__1B *)li__1B__)->li__BF=li__GLB;
  if ((void *)NULL == (void *)li__GLB) {
    li__VNB((&__string_23));
  };
  if (((__li__2B *)li__2B__)->li__WC) {
    li__VE=((__li__1B *)li__1B__)->li__BF;
    li__AD=li__GJB((__li__K)((__li__K)((&__string_24)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__VE)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_24));
    li__45D(((__li__FC *)li__AD),li__VE);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__IK));
  };
  li__ZAD=li__MPB();
  li__M4D(((__li__FC *)li__ZAD),((__li__1B *)li__1B__)->li__BF);
  li__EJN(((__li__FC *)li__ZAD));
  li__M4D(((__li__FC *)li__ZAD),(&__string_25));
  if (((__li__2B *)li__2B__)->li__WC) {
    li__AD=li__GJB((__li__K)((__li__K)((&__string_26)->li__LB.li__BC + 1) + (__li__K)(((__li__FC *)li__ZAD)->li__GC.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_26));
    li__45D(((__li__FC *)li__AD),li__ZAD);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__IK));
  };
  li__Q4=li__BCE(((__li__FC *)li__ZAD));
  remove((char*)(li__Q4));
  li__0YI=li__I__;
  li__JME=li__ADC(li__ZAD);
  if (li__JME != (void *)NULL) {
    li__0YI=li__B__;
    fclose((FILE*)((li__JME)));
  };
  if (li__0YI) {
    li__AD=li__GJB((__li__K)((__li__K)((&__string_27)->li__LB.li__BC + 1) + (__li__K)(((__li__FC *)li__ZAD)->li__GC.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_27));
    li__45D(((__li__FC *)li__AD),li__ZAD);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__0LC(li__IK);
  };
  li__EQB(&(li__AEB),li__ZAD);
  li__GLB=li__VCB((&__string_28));
  ((__li__1B *)li__1B__)->li__3P=li__GLB;
  if ((void *)NULL == (void *)li__GLB) {
    li__VNB((&__string_29));
    li__MBP=li__B__;
  } else /* FALSE */ {
    li__MBP=li__I__;
  };
  if (! li__MBP) {
    li__VE=((__li__1B *)li__1B__)->li__3P;
    if ((void *)(&__string_30) == (void *)li__VE) {
      li__RQ=((__li__1B *)li__1B__)->li__5I;
      li__IM=((void *)(&__string_7) == (void *)li__RQ);
    } else /* FALSE */ {
      li__IM=li__I__;
    };
    if (li__IM) {
      ((__li__1B *)li__1B__)->li__3P=(&__string_31);
    };
  };
  if (((__li__2B *)li__2B__)->li__WC) {
    li__VE=((__li__1B *)li__1B__)->li__3P;
    li__AD=li__GJB((__li__K)((__li__K)((&__string_32)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__VE)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__AD),(&__string_32));
    li__45D(((__li__FC *)li__AD),li__VE);
    li__IK=li__2GE(((__li__FC *)li__AD),(&__string_4));
    li__MMI(((__li__FC *)li__IK));
  };
  li__41((&__string_33));
  print_char('\n');
  li__YBB(((__li__1B *)li__1B__)->li__HN);
  li__ZAD=li__MPB();
  li__M4D(((__li__FC *)li__ZAD),(&__string_34));
  li__3XC(li__ZAD);
  li__EQB(&(li__AEB),li__ZAD);
  li__GLB=((__li__1B *)li__1B__)->li__3P;
  if ((void *)(&__string_31) == (void *)li__GLB) {
    li__3XB((&__string_35));
    li__MBP=li__B__;
  } else /* FALSE */ {
    li__MBP=li__I__;
  };
  if (li__MBP) {
    li__MBP=li__B__;
  } else /* FALSE */ {
    li__VE=((__li__1B *)li__1B__)->li__3P;
    if ((void *)(&__string_36) == (void *)li__VE) {
      li__3XB((&__string_37));
      li__IM=li__B__;
    } else /* FALSE */ {
      li__IM=li__I__;
    };
    li__MBP=li__IM;
  };
  if (! li__MBP) {
    li__VE=((__li__1B *)li__1B__)->li__5I;
    if ((void *)(&__string_7) == (void *)li__VE) {
      li__3XB((&__string_35));
    } else /* FALSE */ {
      li__VOD((&__string_35));
      li__VOD((&__string_37));
      li__VOD((&__string_38));
    };
  };
  if (((__li__2B *)li__2B__)->li__WC) {
    if ((void *)NULL == (void *)((__li__1B *)li__1B__)->li__JF) {
      li__41((&__string_39));
      print_char('\n');
    };
  };
  li__41((&__string_40));
  print_char('\n');
  li__YBB(((__li__1B *)li__1B__)->li__UD);
  li__ZAD=li__MPB();
  li__0YI=li__DYC((&__string_41),li__ZAD);
  if (! li__0YI) {
    li__VNB((&__string_42));
  };
  li__XKB=li__01B((&__string_43),li__ZAD,(&__string_41));
  li__T2B:
  {
    li__1GX=((__li__FC *)li__ZAD);
    if (((__li__MB *)li__1GX->li__GC.li__CC)[li__XKB] != '\"') {
      li__4GX=((__li__FC *)li__ZAD);
      li__0ZP(li__4GX,li__XKB,li__XKB);
      goto li__T2B;
    };
  };
  li__XBP(((__li__FC *)li__ZAD),((__li__1B *)li__1B__)->li__5I,li__XKB);
  li__B3B((&__string_41),li__ZAD);
  li__EQB(&(li__AEB),li__ZAD);
  li__41((&__string_44));
  print_char('\n');
  li__YBB(((__li__1B *)li__1B__)->li__0N);
  li__YBB((&__string_45));
  li__ZAD=li__MPB();
  li__0YI=li__DYC((&__string_46),li__ZAD);
  if (! li__0YI) {
    li__VNB((&__string_47));
  };
  li__XKB=li__01B((&__string_48),li__ZAD,(&__string_46));
  li__GED=li__XKB;
  li__GLB=(&__string_49);
  li__GK=((__li__1B *)li__1B__)->li__5I;
  if ((void *)(&__string_9) == (void *)li__GK) {
    li__GLB=(&__string_50);
  };
  li__Z4B:
  {
    li__1GX=((__li__FC *)li__ZAD);
    if (((__li__MB *)li__1GX->li__GC.li__CC)[li__GED] != '\"') {
      li__4GX=((__li__FC *)li__ZAD);
      li__0ZP(li__4GX,li__GED,li__GED);
      goto li__Z4B;
    };
  };
  li__XBP(((__li__FC *)li__ZAD),li__GLB,li__XKB);
  li__XKB=li__01B((&__string_51),li__ZAD,(&__string_46));
  li__GED=li__XKB;
  li__GLB=(&__string_52);
  li__GK=((__li__1B *)li__1B__)->li__5I;
  if ((void *)(&__string_9) == (void *)li__GK) {
    li__GLB=(&__string_53);
  };
  li__U5B:
  {
    li__1GX=((__li__FC *)li__ZAD);
    if (((__li__MB *)li__1GX->li__GC.li__CC)[li__GED] != ',') {
      li__4GX=((__li__FC *)li__ZAD);
      li__0ZP(li__4GX,li__GED,li__GED);
      goto li__U5B;
    };
  };
  li__XBP(((__li__FC *)li__ZAD),li__GLB,li__XKB);
  li__B3B((&__string_46),li__ZAD);
  li__EQB(&(li__AEB),li__ZAD);
  li__GLB=((__li__1B *)li__1B__)->li__3P;
  if ((void *)li__GLB != (void *)(&__string_54)) {
    li__41((&__string_55));
    print_char('\n');
    li__YBB(((__li__1B *)li__1B__)->li__UD);
    li__YBB((&__string_56));
    li__AD=li__MPB();
    li__MBP=li__DYC((&__string_57),li__AD);
    if (! li__MBP) {
      li__VNB((&__string_58));
    };
    li__KNC:
    {
      li__4GX=((__li__FC *)li__AD);
      if (((__li__MB *)li__4GX->li__GC.li__CC)[0] != '\n') {
        li__HGP=((__li__FC *)li__AD);
        if (1 > li__HGP->li__GC.li__BC) {
          li__HGP->li__GC.li__BC=(__li__K)(- 1);
        } else /* FALSE */ {
          li__0ZP(li__HGP,0,0);
        };
        goto li__KNC;
      };
    };
    li__VE=((__li__1B *)li__1B__)->li__3P;
    li__IK=li__GJB((__li__K)((__li__K)((&__string_59)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__VE)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__IK),(&__string_59));
    li__45D(((__li__FC *)li__IK),li__VE);
    li__0DP(((__li__FC *)li__AD),li__IK,0);
    li__B3B((&__string_57),li__AD);
    li__EQB(&(li__AEB),li__AD);
  } else /* FALSE */ {
    li__41((&__string_60));
    print_char('\n');
  };
  li__41((&__string_61));
  print_char('\n');
  li__YBB(((__li__1B *)li__1B__)->li__0N);
  li__ZAD=li__MPB();
  li__M4D(((__li__FC *)li__ZAD),((__li__1B *)li__1B__)->li__HN);
  li__EJN(((__li__FC *)li__ZAD));
  li__M4D(((__li__FC *)li__ZAD),(&__string_62));
  li__3XC(li__ZAD);
  li__EQB(&(li__AEB),li__ZAD);
  li__41((&__string_63));
  print_char('\n');
  li__YBB(((__li__1B *)li__1B__)->li__UD);
  li__YBB((&__string_64));
  li__YBB((&__string_65));
  li__ZAD=li__MPB();
  li__M4D(((__li__FC *)li__ZAD),((__li__1B *)li__1B__)->li__0N);
  li__EJN(((__li__FC *)li__ZAD));
  li__M4D(((__li__FC *)li__ZAD),(&__string_66));
  li__KZC(li__ZAD);
  li__EQB(&(li__AEB),li__ZAD);
  li__ZAD=li__MPB();
  li__M4D(((__li__FC *)li__ZAD),((__li__1B *)li__1B__)->li__HN);
  li__EJN(((__li__FC *)li__ZAD));
  li__M4D(((__li__FC *)li__ZAD),(&__string_67));
  li__3XC(li__ZAD);
  li__EQB(&(li__AEB),li__ZAD);
  li__ZAD=li__MPB();
  li__M4D(((__li__FC *)li__ZAD),((__li__1B *)li__1B__)->li__UD);
  li__EJN(((__li__FC *)li__ZAD));
  li__M4D(((__li__FC *)li__ZAD),(&__string_68));
  li__KZC(li__ZAD);
  li__EQB(&(li__AEB),li__ZAD);
  li__41((&__string_69));
  print_char('\n');
  li__41((&__string_70));
  print_char('\n');
  li__41((&__string_71));
  print_char('\n');
  li__GLB=((__li__1B *)li__1B__)->li__JF;
  li__ZAD=li__GJB((__li__K)((__li__K)((&__string_72)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__GLB)->li__LB.li__BC + 1)));
  li__M4D(((__li__FC *)li__ZAD),(&__string_72));
  li__45D(((__li__FC *)li__ZAD),li__GLB);
  li__MMI(((__li__FC *)li__ZAD));
  return(0);
}


void die_with_code(__li__K li__SDD)
/* (Expanded INTEGER{li__K}) Void Recursive, Inlinable. NO CONTEXT! */
{
  exit((li__SDD));
}

void print_char(__li__MB li__XCD)
/* (Expanded CHARACTER{li__MB}) Void No recursive, Inlinable. NO CONTEXT! */
{
  fputc((int)(li__XCD),stdout);
}

void bug_compilo_042()
/* () Void Recursive, Inlinable. NO CONTEXT! */
{
  print_string("Call on NULL\n(Do not use `-boost' option for print stack trace)\n"); die_with_code(1);
}

static __li__FC* li__GJB(__li__K li__IJB)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__50C,*li__JJB;
  __li__RB li__A1C;
  __li__C1C li__C2C;
  __li__FC *li__A3C;
 li__50C=(__li__FC *)NULL;
  li__A1C=((__li__RB )(NULL));
  li__C2C=((__li__C1C )sizeof(__li__FC));
  if (0 == li__C2C) {
    li__50C=li__FC__;
  } else /* FALSE */ {
    li__A1C=((__li__RB )(malloc(((li__C2C) + 3) & ~3)));
    li__Z2C=(__li__C1C)(li__Z2C - (__li__C1C)(((__li__C1C )0) - li__C2C));
    li__22C=(__li__C1C)(li__22C - (__li__C1C)(((__li__C1C )0) - li__C2C));
    li__A3C=((__li__FC *)li__A1C);
    li__50C=li__A3C;
    *(li__A3C) = *(li__FC__);
  };
  li__UAC(((__li__FC *)li__50C),li__IJB);
  li__JJB=li__50C;
  return(li__JJB);
}

static __li__FB** li__CRJ(__li__K li__ERJ)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__QRJ,li__PGM;
  __li__FB **li__TJK;
  __li__FB **li__FRJ;
 li__TJK=((__li__FB **)((__li__RB )(malloc(((__li__K)(li__ERJ * ((__li__K )(sizeof(void *)))))))));
  li__QRJ=(__li__K)(li__ERJ - 1);
  li__PGM=li__QRJ;
  while ((li__PGM >= 0)) {
    li__TJK[li__PGM]=NULL;
    li__PGM=(__li__K)(li__PGM - 1);
  };
  li__FRJ=li__TJK;
  return(li__FRJ);
}

static void li__DOE(__li__FC *li__EOE,__li__MB *li__FOE)
/* (Strict STRING_BUFFER{li__FC},Strict NATIVE_ARRAY(Expanded CHARACTER){NULLxli__VB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__GOE,li__YLG,li__SHX;
  __li__MB li__0OE;
  __li__MB *li__QLG;
  __li__MB *li__RHX;
 li__GOE=0;
  li__EOE->li__GC.li__BC=(__li__K)(- 1);
  while ((((__li__MB *)li__FOE)[li__GOE] != '\0')) {
    li__0OE=((__li__MB *)li__FOE)[li__GOE];
    if (li__EOE->li__12 == (__li__K)(li__EOE->li__GC.li__BC + 1)) {
      if (0 == li__EOE->li__12) {
        li__EOE->li__12=32;
        li__QLG=li__HHG(32);
        li__EOE->li__GC.li__CC=li__QLG;
      } else /* FALSE */ {
        li__YLG=(__li__K)(li__EOE->li__12 << 1);
        li__QLG=((__li__MB *)li__EOE->li__GC.li__CC);
        li__SHX=li__EOE->li__12;
        li__RHX=((__li__MB *)((__li__RB )(realloc((((__li__RB )li__QLG)),(li__YLG)))));
        li__IWG(li__RHX,li__SHX,(__li__K)(li__YLG - 1));
        li__EOE->li__GC.li__CC=li__RHX;
        li__EOE->li__12=li__YLG;
      };
    };
    li__EOE->li__GC.li__BC=(__li__K)(li__EOE->li__GC.li__BC + 1);
    ((__li__MB *)li__EOE->li__GC.li__CC)[li__EOE->li__GC.li__BC]=li__0OE;
    li__GOE=(__li__K)(li__GOE + 1);
  };
}

static __li__FB* li__12D(__li__FC *li__22D)
/* (Strict STRING_BUFFER{li__FC}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__FB *li__AWE,*li__BWE;
  __li__FB *li__JWE,*li__DYE,*li__32D;
  __li__GB *li__XHX;
  __li__K li__2VE,li__VEG,li__YEG,li__G5G,li__4EG,li__2II;
  __li__3VE *li__5VE;
  __li__MB *li__NUV,*li__4AI,*li__YII;
  __li__C li__TXE,li__HAI,li__QXE;
 li__2VE=0;
  li__5VE=(__li__3VE *)NULL;
  li__AWE=(__li__FB *)NULL;
  li__BWE=(__li__FB *)NULL;
  if (0 == li__CWE) {
    li__JWE=li__LZF(li__22D);
    li__AWE=li__JWE;
    li__K0F(li__JWE);
  } else /* FALSE */ {
    li__VEG=0;
    li__YEG=li__JPG(li__22D->li__GC.li__BC);
    li__G5G=0;
    li__XHX=&(li__22D->li__GC);
    while ((li__G5G <= li__YEG)) {
      li__4EG=(__li__K)(li__VEG << 2);
      li__VEG=(__li__K)(li__4EG + ((__li__K )((__li__X1C )((__li__MB *)li__XHX->li__CC)[li__G5G])));
      li__G5G=(__li__K)(li__G5G + 1);
    };
    li__YEG=(__li__K)(li__VEG & 2147483647);
    li__2VE=li__YEG;
    li__5VE=(__li__3VE *)((void **)li__UWE)[(__li__K)(li__YEG % li__CWE)];
    li__VEG=li__22D->li__GC.li__BC;
    li__YEG=li__22D->li__GC.li__BC;
    li__NUV=li__22D->li__GC.li__CC;
    li__G5G=li__22D->li__GC.li__BC;
    li__X3F:
    {
      if ((void *)NULL == (void *)li__5VE) {
        li__TXE=li__B__;
      } else /* FALSE */ {
        li__BWE=li__5VE->li__DXE;
        if (li__BWE /* Always NULL */ ->li__GXE == li__2VE) {
          li__HAI=li__I__;
          if (li__VEG == li__BWE /* Always NULL */ ->li__LB.li__BC) {
            if (li__YEG == (__li__K)(- 1)) {
              li__HAI=li__B__;
            } else /* FALSE */ {
              li__4AI=li__BWE /* Always NULL */ ->li__LB.li__CC;
              li__YII=((__li__MB *)li__NUV);
              li__2II=li__G5G;
              while (((li__2II >= 0) && (li__YII[li__2II] == ((__li__MB *)li__4AI)[li__2II]))) {
                li__2II=(__li__K)(li__2II - 1);
              };
              li__HAI=(li__2II < 0);
            };
          };
          li__QXE=li__HAI;
        } else /* FALSE */ {
          li__QXE=li__I__;
        };
        li__TXE=li__QXE;
      };
      if (! li__TXE) {
        li__5VE=li__5VE->li__0XE;
        goto li__X3F;
      };
    };
    if ((void *)NULL == (void *)li__5VE) {
      li__DYE=li__LZF(li__22D);
      li__AWE=li__DYE;
      li__K0F(li__DYE);
    } else /* FALSE */ {
      li__AWE=li__5VE->li__DXE;
    };
  };
  li__32D=li__AWE;
  return(li__32D);
}

static void li__41(__li__FB *li__51)
/* (Strict STRING_ALIAS{li__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__A2,li__0BD;
 li__A2=li__51->li__LB.li__BC;
  li__0BD=0;
  while ((li__0BD <= li__A2)) {
    print_char(((__li__MB *)li__51->li__LB.li__CC)[li__0BD]);
    li__0BD=(__li__K)(li__0BD + 1);
  };
}

static void li__3F(__li__FC *li__5F)
/* (Strict STRING_BUFFER{NULLxli__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__NDE;
  __li__GB *li__D1W,*li__E1W,*li__F1W;
  __li__MB *li__02;
 li__02=li__BCE(((__li__FC *)li__5F));
  getcwd((li__02),(li__5F->li__12));
  li__NDE=((__li__FC *)li__5F);
  li__NDE->li__GC.li__BC=(__li__K)(- 1);
  li__02=li__NDE->li__GC.li__CC;
  li__D1W=&(li__NDE->li__GC);
  li__E1W=&(li__NDE->li__GC);
  li__F1W=&(li__NDE->li__GC);
  while ((((__li__MB *)li__02)[(__li__K)(li__D1W->li__BC + 1)] != '\0')) {
    li__E1W->li__BC=(__li__K)(li__F1W->li__BC + 1);
  };
  li__DEE(((__li__FC *)li__5F),'/');
  ;
}

static void li__M4D(__li__FC *li__N4D,__li__FB *li__O4D)
/* (Strict STRING_BUFFER{li__FC},Strict STRING_ALIAS{NULLxli__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__X4D,li__Z4D,li__1HX;
  __li__MB *li__I5D;
  __li__MB *li__0HX;
 li__X4D=(__li__K)(((__li__FB *)li__O4D)->li__LB.li__BC + 1);
  li__Z4D=(__li__K)((__li__K)(li__N4D->li__GC.li__BC + 1) + li__X4D);
  if (li__N4D->li__12 < li__Z4D) {
    if (0 == li__N4D->li__12) {
      li__N4D->li__12=li__Z4D;
      li__I5D=li__HHG(li__Z4D);
      li__N4D->li__GC.li__CC=li__I5D;
    } else /* FALSE */ {
      li__I5D=((__li__MB *)li__N4D->li__GC.li__CC);
      li__1HX=li__N4D->li__12;
      li__0HX=((__li__MB *)((__li__RB )(realloc((((__li__RB )li__I5D)),(li__Z4D)))));
      li__IWG(li__0HX,li__1HX,(__li__K)(li__Z4D - 1));
      li__N4D->li__GC.li__CC=li__0HX;
      li__N4D->li__12=li__Z4D;
    };
  };
  li__UZE(((__li__MB *)li__N4D->li__GC.li__CC),li__O4D->li__LB.li__CC,(__li__K)(li__N4D->li__GC.li__BC + 1),li__X4D);
  li__N4D->li__GC.li__BC=(__li__K)(li__Z4D - 1);
}

static void li__45D(__li__FC *li__55D,void *li__AAE)
/* (Strict STRING_BUFFER{li__FC},STRING{NULLxli__FBxli__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__JAE,li__LAE,li__5DX;
  __li__MB *li__0AE,*li__LBE;
  __li__MB *li__4DX;
 if (((struct ___OBJ *)li__AAE)->__id==__li__FB__) {
    li__JAE=(__li__K)(((__li__FB *)li__AAE)->li__LB.li__BC + 1);
  } else /* STRING_BUFFER */ {
    li__JAE=(__li__K)(((__li__FC *)li__AAE)->li__GC.li__BC + 1);
  };
  li__LAE=(__li__K)((__li__K)(li__55D->li__GC.li__BC + 1) + li__JAE);
  if (li__55D->li__12 < li__LAE) {
    if (0 == li__55D->li__12) {
      li__55D->li__12=li__LAE;
      li__0AE=li__HHG(li__LAE);
      li__55D->li__GC.li__CC=li__0AE;
    } else /* FALSE */ {
      li__0AE=((__li__MB *)li__55D->li__GC.li__CC);
      li__5DX=li__55D->li__12;
      li__4DX=((__li__MB *)((__li__RB )(realloc((((__li__RB )li__0AE)),(li__LAE)))));
      li__IWG(li__4DX,li__5DX,(__li__K)(li__LAE - 1));
      li__55D->li__GC.li__CC=li__4DX;
      li__55D->li__12=li__LAE;
    };
  };
  li__0AE=li__55D->li__GC.li__CC;
  if (((struct ___OBJ *)li__AAE)->__id==__li__FB__) {
    li__LBE=((__li__FB *)li__AAE)->li__LB.li__CC;
  } else /* STRING_BUFFER */ {
    li__LBE=((__li__FC *)li__AAE)->li__GC.li__CC;
  };
  li__UZE(((__li__MB *)li__0AE),li__LBE,(__li__K)(li__55D->li__GC.li__BC + 1),li__JAE);
  li__55D->li__GC.li__BC=(__li__K)(li__LAE - 1);
}

static __li__FC* li__2GE(__li__FC *li__3GE,void *li__4GE)
/* (Strict STRING_BUFFER{li__FC},STRING{li__FB}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__MHE,*li__OTI,*li__5GE;
  __li__K li__YTI,li__0TI,li__3HG;
  __li__MB *li__JUI;
  __li__MB *li__FWG;
 li__MHE=li__GJB((__li__K)((__li__K)(li__3GE->li__GC.li__BC + 1) + (__li__K)(((__li__FB *)li__4GE)->li__LB.li__BC + 1)));
  li__OTI=((__li__FC *)li__MHE);
  li__YTI=(__li__K)(li__3GE->li__GC.li__BC + 1);
  li__0TI=(__li__K)((__li__K)(li__OTI->li__GC.li__BC + 1) + li__YTI);
  if (li__OTI->li__12 < li__0TI) {
    if (0 == li__OTI->li__12) {
      li__OTI->li__12=li__0TI;
      li__JUI=li__HHG(li__0TI);
      li__OTI->li__GC.li__CC=li__JUI;
    } else /* FALSE */ {
      li__JUI=((__li__MB *)li__OTI->li__GC.li__CC);
      li__3HG=li__OTI->li__12;
      li__FWG=((__li__MB *)((__li__RB )(realloc((((__li__RB )li__JUI)),(li__0TI)))));
      li__IWG(li__FWG,li__3HG,(__li__K)(li__0TI - 1));
      li__OTI->li__GC.li__CC=li__FWG;
      li__OTI->li__12=li__0TI;
    };
  };
  li__UZE(((__li__MB *)li__OTI->li__GC.li__CC),li__3GE->li__GC.li__CC,(__li__K)(li__OTI->li__GC.li__BC + 1),li__YTI);
  li__OTI->li__GC.li__BC=(__li__K)(li__0TI - 1);
  li__45D(((__li__FC *)li__MHE),li__4GE);
  li__5GE=li__MHE;
  ;
  return(li__5GE);
}

static void li__MMI(__li__FC *li__NMI)
/* (Strict STRING_BUFFER{li__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__MFJ,li__L4J;
 li__MFJ=li__NMI->li__GC.li__BC;
  li__L4J=0;
  while ((li__L4J <= li__MFJ)) {
    print_char(((__li__MB *)li__NMI->li__GC.li__CC)[li__L4J]);
    li__L4J=(__li__K)(li__L4J + 1);
  };
  print_char('\n');
}

static __li__FC* li__MPB()
/* () With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__PPB,*li__XPB,*li__1IX,*li__OPB;
  __li__K li__0IX;
  __li__C li__XAX;
 li__PPB=(__li__FC *)NULL;
  li__XAX=(li__AEB.li__IQB < 0);
  if (li__XAX) {
    li__XPB=li__GJB(512);
    li__PPB=li__XPB;
  } else /* FALSE */ {
    li__0IX=li__AEB.li__IQB;
    li__1IX=(__li__FC *)((void **)li__AEB.li__HRB)[li__0IX];
    li__AEB.li__IQB=(__li__K)(li__AEB.li__IQB - 1);
    li__PPB=li__1IX;
    ((__li__FC *)li__1IX)->li__GC.li__BC=(__li__K)(- 1);
    ;
  };
  li__OPB=li__PPB;
  return(li__OPB);
}

static void li__EQB(__li__ZDB *li__FQB,__li__FC *li__GQB)
/* (Expanded ARRAY(STRING_BUFFER){li__ZDB},Strict STRING_BUFFER{NULLxli__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__KQM,li__RRB,li__VFK,li__DSM;
  __li__C li__NQB,li__XQB;
  __li__PB li__WQB;
  __li__ZDB *li__SQB,*li__CRB;
  __li__PB li__4QB;
  __li__PB li__JRB;
  __li__PB li__WRB;
  void **li__2EL;
  void **li__QRB,**li__0EK;
 li__NQB=((__li__K)(li__FQB->li__IQB + 1) < li__FQB->li__KQB);
  li__WQB.self=li__FQB;
  if (li__NQB) {
    li__SQB=((__li__ZDB *)li__WQB.self);
    li__SQB->li__IQB=(__li__K)(li__SQB->li__IQB + 1);
    li__XQB=li__B__;
  } else /* FALSE */ {
    li__XQB=li__I__;
  };
  li__4QB.self=li__FQB;
  li__JRB.self=li__FQB;
  li__WRB.self=li__FQB;
  if (! li__XQB) {
    if (0 == ((__li__ZDB *)li__4QB.self)->li__KQB) {
      li__CRB=((__li__ZDB *)li__JRB.self);
      li__2EL=((void **)((__li__RB )(malloc(((__li__K)(((__li__K )(sizeof(void *))) << 1))))));
      li__KQM=1;
      while ((li__KQM >= 0)) {
        li__2EL[li__KQM]=NULL;
        li__KQM=(__li__K)(li__KQM - 1);
      };
      li__CRB->li__HRB=li__2EL;
      li__CRB->li__KQB=2;
      li__CRB->li__IQB=0;
    } else /* FALSE */ {
      li__CRB=((__li__ZDB *)li__WRB.self);
      li__KQM=(__li__K)(li__CRB->li__KQB << 1);
      li__QRB=li__CRB->li__HRB;
      li__RRB=li__CRB->li__KQB;
      li__0EK=((void **)li__QRB);
      li__2EL=((void **)((__li__RB )(realloc((((__li__RB )li__0EK)),((__li__K)(li__KQM * ((__li__K )(sizeof(void *)))))))));
      li__VFK=(__li__K)(li__KQM - 1);
      li__DSM=li__RRB;
      while ((li__DSM <= li__VFK)) {
        li__2EL[li__DSM]=NULL;
        li__DSM=(__li__K)(li__DSM + 1);
      };
      li__CRB->li__HRB=li__2EL;
      li__CRB->li__KQB=li__KQM;
      li__CRB->li__IQB=(__li__K)(li__CRB->li__IQB + 1);
    };
  };
  ((void **)li__FQB->li__HRB)[li__FQB->li__IQB]=li__GQB;
  ;
}

static __li__C li__QK(__li__FB *li__RK,__li__MB li__SK)
/* (Strict STRING_ALIAS{li__FB},Expanded CHARACTER{li__MB}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__VK,li__DAB;
  __li__MB *li__UK,*li__W5;
  __li__C li__TK;
 li__UK=li__RK->li__LB.li__CC;
  li__VK=li__RK->li__LB.li__BC;
  li__W5=((__li__MB *)li__UK);
  li__DAB=li__VK;
  while ((! ((li__DAB < 0) || (li__SK == li__W5[li__DAB])))) {
    li__DAB=(__li__K)(li__DAB - 1);
  };
  li__TK=(li__DAB >= 0);
  return(li__TK);
}

static void li__VNB(void *li__XNB)
/* (STRING{li__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
  li__41((__li__FB *)li__XNB);
  print_char('\n');
  if (! ((__li__2B *)li__2B__)->li__WC) {
    li__41((&__string_73));
    print_char('\n');
  };
  exit((1));
}

static void li__YBB(__li__FB *li__0BB)
/* (Strict STRING_ALIAS{NULLxli__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__UBX,*li__BCB;
  __li__MB *li__DLE;
 if (((__li__2B *)li__2B__)->li__WC) {
    li__UBX=li__GJB((__li__K)((__li__K)((&__string_74)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__0BB)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__UBX),(&__string_74));
    li__45D(((__li__FC *)li__UBX),li__0BB);
    li__BCB=li__2GE(((__li__FC *)li__UBX),(&__string_75));
    li__MMI(((__li__FC *)li__BCB));
  };
  li__UBX=((__li__FC *)li__DDB);
  li__UBX->li__GC.li__BC=li__0BB->li__LB.li__BC;
  if (li__UBX->li__GC.li__BC >= 0) {
    if (li__UBX->li__12 < (__li__K)(li__UBX->li__GC.li__BC + 1)) {
      li__DLE=li__HHG((__li__K)(li__UBX->li__GC.li__BC + 1));
      li__UBX->li__GC.li__CC=li__DLE;
      li__UBX->li__12=(__li__K)(li__UBX->li__GC.li__BC + 1);
    };
    li__GVF(((__li__MB *)li__UBX->li__GC.li__CC),li__0BB->li__LB.li__CC,li__UBX->li__GC.li__BC);
  };
  li__DLE=li__BCE(((__li__FC *)li__DDB));
  if (((__li__K )(chdir((char*)(li__DLE)))) != 0) {
    li__VNB((&__string_76));
  };
  li__3F(((__li__2B *)li__2B__)->li__KC);
}

static __li__FB* li__VCB(void *li__XCB)
/* (STRING{li__FB}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__FB *li__0CB,*li__GDB,*li__YCB;
  __li__MB *li__3CB;
 li__0CB=(__li__FB *)NULL;
  li__3CB=((__li__MB *)(getenv((char*)(((__li__FB *)li__XCB)->li__LB.li__CC))));
  if ((void *)li__3CB != (void *)NULL) {
    li__DOE(((__li__FC *)li__DDB),li__3CB);
    li__GDB=li__12D(((__li__FC *)li__DDB));
    li__0CB=li__GDB;
  };
  li__YCB=li__0CB;
  return(li__YCB);
}

static void li__EJN(__li__FC *li__FJN)
/* (Strict STRING_BUFFER{li__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__4HX;
  __li__C li__SJN;
 if (li__FJN->li__GC.li__BC == (__li__K)(- 1)) {
    li__SJN=li__B__;
  } else /* FALSE */ {
    li__4HX=li__FJN->li__GC.li__BC;
    li__SJN=(((__li__MB *)li__FJN->li__GC.li__CC)[li__4HX] != '/');
  };
  if (li__SJN) {
    li__DEE(li__FJN,'/');
  };
  ;
}

static __li__MB* li__BCE(__li__FC *li__CCE)
/* (Strict STRING_BUFFER{li__FC}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__MB *li__DCE;
 if (li__CCE->li__12 > (__li__K)(li__CCE->li__GC.li__BC + 1)) {
    ((__li__MB *)li__CCE->li__GC.li__CC)[(__li__K)(li__CCE->li__GC.li__BC + 1)]='\0';
  } else /* FALSE */ {
    li__DEE(li__CCE,'\0');
    li__CCE->li__GC.li__BC=(__li__K)(li__CCE->li__GC.li__BC - 1);
  };
  li__DCE=li__CCE->li__GC.li__CC;
  ;
  return(li__DCE);
}

static __li__RB li__ADC(void *li__CDC)
/* (STRING{NULLxli__FBxli__FC}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__RB li__DDC;
  __li__MB *li__FDC;
 if (((struct ___OBJ *)li__CDC)->__id==__li__FB__) {
    li__FDC=((__li__FB *)li__CDC)->li__LB.li__CC;
  } else /* STRING_BUFFER */ {
    li__FDC=li__BCE(((__li__FC *)li__CDC));
  };
  li__DDC=((__li__RB )(fopen((char*)(li__FDC),"rb")));
  return(li__DDC);
}

static void li__0LC(__li__FC *li__2LC)
/* (Strict STRING_BUFFER{NULLxli__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
  li__MMI(((__li__FC *)li__2LC));
  if (! ((__li__2B *)li__2B__)->li__WC) {
    li__41((&__string_73));
    print_char('\n');
  };
  exit((1));
}

static __li__K li__3XC(__li__FC *li__5XC)
/* (Strict STRING_BUFFER{NULLxli__FC}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__MFD,li__AYC;
 if (((__li__2B *)li__2B__)->li__WC) {
    li__MMI(((__li__FC *)li__5XC));
  };
  fflush(stdout);
  li__MFD=li__CHD(li__5XC,li__I__);
  if (((__li__2B *)li__2B__)->li__WC && (li__MFD != 0)) {
    li__41((&__string_77));
    li__PQF(li__MFD);
  };
  if (li__MFD != 0) {
    exit((li__MFD));
  };
  li__AYC=li__MFD;
  return(li__AYC);
}

static void li__3XB(__li__FB *li__5XB)
/* (Strict STRING_ALIAS{li__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__ZBX,*li__DYB,*li__4BX,*li__LYB,*li__DCX,*li__GZB;
  __li__FC *li__DIX,*li__GIX;
  __li__RB li__2ND;
  __li__K li__BYB,li__BIX,li__W0B;
  __li__C li__RYB,li__3ZB;
 li__BYB=0;
  li__ZBX=li__GJB((__li__K)((__li__K)((&__string_78)->li__LB.li__BC + 1) + (__li__K)(li__5XB->li__LB.li__BC + 1)));
  li__M4D(((__li__FC *)li__ZBX),(&__string_78));
  li__45D(((__li__FC *)li__ZBX),li__5XB);
  li__DYB=li__2GE(((__li__FC *)li__ZBX),(&__string_4));
  li__MMI(((__li__FC *)li__DYB));
  if (((__li__2B *)li__2B__)->li__WC) {
    li__4BX=li__GJB((__li__K)((__li__K)((&__string_79)->li__LB.li__BC + 1) + (__li__K)(li__5XB->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__4BX),(&__string_79));
    li__45D(((__li__FC *)li__4BX),li__5XB);
    li__LYB=li__2GE(((__li__FC *)li__4BX),(&__string_4));
    li__MMI(((__li__FC *)li__LYB));
  };
  li__YBB(((__li__1B *)li__1B__)->li__BF);
  li__RYB=li__RFC(li__5XB);
  if (! li__RYB) {
    if (((__li__2B *)li__2B__)->li__WC) {
      li__DCX=li__GJB((__li__K)((__li__K)((&__string_80)->li__LB.li__BC + 1) + (__li__K)(li__5XB->li__LB.li__BC + 1)));
      li__M4D(((__li__FC *)li__DCX),(&__string_80));
      li__45D(((__li__FC *)li__DCX),li__5XB);
      li__GZB=li__2GE(((__li__FC *)li__DCX),(&__string_4));
      li__MMI(((__li__FC *)li__GZB));
    };
    li__2ND=((__li__RB )(fopen((char*)(li__5XB->li__LB.li__CC),"w+b")));
    if (li__2ND != (void *)NULL) {
      fclose((FILE*)((li__2ND)));
    };
  };
  li__RYB=li__RFC(li__5XB);
  if (li__RYB) {
    ((__li__1B *)li__1B__)->li__JF=li__5XB;
    li__4BX=li__MPB();
    li__LYB=li__MPB();
    li__M4D(((__li__FC *)li__LYB),(&__string_81));
    li__IRC(li__LYB,((__li__1B *)li__1B__)->li__HN);
    li__IRC(li__LYB,((__li__1B *)li__1B__)->li__0N);
    li__M4D(((__li__FC *)li__LYB),(&__string_82));
    li__3ZB=li__DYC(li__5XB,li__4BX);
    if (li__3ZB) {
      li__DCX=((__li__FC *)li__4BX);
      li__BIX=li__XTP(li__DCX,(&__string_83));
      li__BYB=li__BIX;
      if (li__BIX < 0) {
        li__M4D(((__li__FC *)li__4BX),(&__string_83));
        li__KHP(((__li__FC *)li__4BX),li__LYB);
      } else /* FALSE */ {
        li__W0B=(__li__K)(li__BIX + (__li__K)((&__string_83)->li__LB.li__BC + 1));
        li__BYB=li__W0B;
        li__ISJ:
        {
          li__DIX=((__li__FC *)li__4BX);
          if (((__li__MB *)li__DIX->li__GC.li__CC)[li__BYB] != '\n') {
            li__GIX=((__li__FC *)li__4BX);
            li__0ZP(li__GIX,li__BYB,li__BYB);
            goto li__ISJ;
          };
        };
        li__DIX=((__li__FC *)li__4BX);
        li__0ZP(li__DIX,li__W0B,li__W0B);
        li__0DP(((__li__FC *)li__4BX),li__LYB,li__W0B);
      };
      li__B3B(li__5XB,li__4BX);
    } else /* FALSE */ {
      li__DCX=li__GJB((__li__K)((__li__K)((&__string_84)->li__LB.li__BC + 1) + (__li__K)(li__5XB->li__LB.li__BC + 1)));
      li__M4D(((__li__FC *)li__DCX),(&__string_84));
      li__45D(((__li__FC *)li__DCX),li__5XB);
      li__GZB=li__2GE(((__li__FC *)li__DCX),(&__string_4));
      li__0LC(li__GZB);
    };
    li__EQB(&(li__AEB),li__LYB);
    li__EQB(&(li__AEB),li__4BX);
  };
}

static void li__VOD(__li__FB *li__XOD)
/* (Strict STRING_ALIAS{li__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__NCX,*li__1OD,*li__SCX,*li__DPD,*li__KGP,*li__HJG;
  __li__FC *li__KIX;
  __li__K li__ZOD,li__YGP,li__NRD;
  __li__C li__HQD,li__VQD;
 li__ZOD=0;
  li__NCX=li__GJB((__li__K)((__li__K)((&__string_78)->li__LB.li__BC + 1) + (__li__K)(li__XOD->li__LB.li__BC + 1)));
  li__M4D(((__li__FC *)li__NCX),(&__string_78));
  li__45D(((__li__FC *)li__NCX),li__XOD);
  li__1OD=li__2GE(((__li__FC *)li__NCX),(&__string_4));
  li__MMI(((__li__FC *)li__1OD));
  if (((__li__2B *)li__2B__)->li__WC) {
    li__SCX=li__GJB((__li__K)((__li__K)((&__string_79)->li__LB.li__BC + 1) + (__li__K)(li__XOD->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__SCX),(&__string_79));
    li__45D(((__li__FC *)li__SCX),li__XOD);
    li__DPD=li__2GE(((__li__FC *)li__SCX),(&__string_4));
    li__MMI(((__li__FC *)li__DPD));
  };
  li__YBB(((__li__1B *)li__1B__)->li__BF);
  li__RFC(li__XOD);
  li__HQD=li__RFC(li__XOD);
  if (li__HQD) {
    ((__li__1B *)li__1B__)->li__JF=li__XOD;
    li__SCX=li__MPB();
    li__DPD=li__MPB();
    li__M4D(((__li__FC *)li__DPD),(&__string_81));
    li__IRC(li__DPD,((__li__1B *)li__1B__)->li__HN);
    li__IRC(li__DPD,((__li__1B *)li__1B__)->li__0N);
    li__M4D(((__li__FC *)li__DPD),(&__string_82));
    li__VQD=li__DYC(li__XOD,li__SCX);
    if (li__VQD) {
      li__KGP=((__li__FC *)li__SCX);
      li__YGP=li__XTP(li__KGP,(&__string_83));
      li__ZOD=li__YGP;
      if (li__YGP < 0) {
        li__M4D(((__li__FC *)li__SCX),(&__string_83));
        li__KHP(((__li__FC *)li__SCX),li__DPD);
      } else /* FALSE */ {
        li__NRD=(__li__K)(li__YGP + (__li__K)((&__string_83)->li__LB.li__BC + 1));
        li__ZOD=li__NRD;
        li__YSJ:
        {
          li__HJG=((__li__FC *)li__SCX);
          if (((__li__MB *)li__HJG->li__GC.li__CC)[li__ZOD] != '\n') {
            li__KIX=((__li__FC *)li__SCX);
            li__0ZP(li__KIX,li__ZOD,li__ZOD);
            goto li__YSJ;
          };
        };
        li__HJG=((__li__FC *)li__SCX);
        li__0ZP(li__HJG,li__NRD,li__NRD);
        li__0DP(((__li__FC *)li__SCX),li__DPD,li__NRD);
      };
      li__B3B(li__XOD,li__SCX);
    } else /* FALSE */ {
      li__KGP=li__GJB((__li__K)((__li__K)((&__string_84)->li__LB.li__BC + 1) + (__li__K)(li__XOD->li__LB.li__BC + 1)));
      li__M4D(((__li__FC *)li__KGP),(&__string_84));
      li__45D(((__li__FC *)li__KGP),li__XOD);
      li__HJG=li__2GE(((__li__FC *)li__KGP),(&__string_4));
      li__0LC(li__HJG);
    };
    li__EQB(&(li__AEB),li__DPD);
    li__EQB(&(li__AEB),li__SCX);
  };
}

static __li__C li__DYC(void *li__FYC,__li__FC *li__GYC)
/* (STRING{li__FB},Strict STRING_BUFFER{NULLxli__FC}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__RB li__MYC;
  __li__K li__YSD;
  __li__C li__IYC,li__HYC;
 li__IYC=li__I__;
  li__MYC=li__ADC(li__FYC);
  if (li__MYC != (void *)NULL) {
    li__IYC=li__B__;
    fseek((FILE*)((li__MYC)),0,SEEK_END);
    li__YSD=((__li__K )(ftell((FILE *)(li__MYC))));
    fseek((FILE*)((li__MYC)),0,SEEK_SET);
    li__UAC(((__li__FC *)li__GYC),li__YSD);
    fread((void *)((li__GYC->li__GC.li__CC)),(size_t)(1), (size_t)((li__YSD)),(FILE*)((li__MYC)));
    ((__li__FC *)li__GYC)->li__GC.li__BC=(__li__K)(li__YSD - 1);
    fclose((FILE*)((li__MYC)));
  };
  li__HYC=li__IYC;
  return(li__HYC);
}

static __li__K li__01B(void *li__21B,__li__FC *li__31B,__li__FB *li__41B)
/* (STRING{li__FB},Strict STRING_BUFFER{NULLxli__FC},Strict STRING_ALIAS{li__FB}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__ADP,*li__UQJ,*li__J2B;
  __li__K li__ODP,li__51B;
 li__ADP=((__li__FC *)li__31B);
  li__ODP=li__XTP(li__ADP,li__21B);
  if (li__ODP < 0) {
    li__UQJ=li__GJB((__li__K)((__li__K)((&__string_85)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__21B)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__UQJ),(&__string_85));
    li__45D(((__li__FC *)li__UQJ),li__21B);
    li__J2B=li__2GE(((__li__FC *)li__UQJ),(&__string_86));
    li__UQJ=li__2GE(((__li__FC *)li__J2B),li__41B);
    li__J2B=li__2GE(((__li__FC *)li__UQJ),(&__string_87));
    li__0LC(li__J2B);
  };
  li__51B=(__li__K)(li__ODP + (__li__K)(((__li__FB *)li__21B)->li__LB.li__BC + 1));
  return(li__51B);
}

static void li__0ZP(__li__FC *li__1ZP,__li__K li__2ZP,__li__K li__3ZP)
/* (Strict STRING_BUFFER{li__FC},Expanded INTEGER{li__K},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__GB *li__PIX,*li__QIX;
  __li__K li__R0P,li__Y0P,li__00P,li__TGS,li__A1P;
  __li__MB li__C1P;
 li__R0P=(__li__K)((__li__K)(li__3ZP - li__2ZP) + 1);
  if (li__R0P > 0) {
    li__Y0P=(__li__K)(li__3ZP + 1);
    li__00P=li__1ZP->li__GC.li__BC;
    li__TGS=li__Y0P;
    li__PIX=&(li__1ZP->li__GC);
    li__QIX=&(li__1ZP->li__GC);
    while ((li__TGS <= li__00P)) {
      li__A1P=(__li__K)(li__TGS - li__R0P);
      li__C1P=((__li__MB *)li__PIX->li__CC)[li__TGS];
      ((__li__MB *)li__QIX->li__CC)[li__A1P]=li__C1P;
      li__TGS=(__li__K)(li__TGS + 1);
    };
    li__1ZP->li__GC.li__BC=(__li__K)(li__1ZP->li__GC.li__BC - li__R0P);
  };
  ;
}

static void li__XBP(__li__FC *li__YBP,__li__FB *li__ZBP,__li__K li__0BP)
/* (Strict STRING_BUFFER{li__FC},Strict STRING_ALIAS{NULLxli__FB},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__1BP,li__MCP;
 li__1BP=li__YBP->li__GC.li__BC;
  li__MCP=(__li__K)(((__li__FB *)li__ZBP)->li__LB.li__BC + 1);
  li__5PP(li__YBP,(__li__K)((__li__K)(li__1BP + li__MCP) + 1));
  if (li__0BP <= li__1BP) {
    li__2CR(((__li__MB *)li__YBP->li__GC.li__CC),li__0BP,li__1BP,li__MCP);
  };
  li__UZE(((__li__MB *)li__YBP->li__GC.li__CC),li__ZBP->li__LB.li__CC,li__0BP,li__MCP);
}

static void li__B3B(__li__FB *li__D3B,__li__FC *li__E3B)
/* (Strict STRING_ALIAS{li__FB},Strict STRING_BUFFER{NULLxli__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__2CX,*li__O3B,*li__VMP;
  __li__RB li__T3B;
  __li__11C li__IZF,li__JAJ,li__51M;
  __li__FB *li__AUE;
  __li__K li__U3B,li__W3B,li__MAJ,li__NAJ;
  __li__X1C li__Z4M,li__NXL;
  __li__MB li__INP,li__JNP;
 if (((__li__2B *)li__2B__)->li__WC) {
    li__2CX=li__GJB((__li__K)((__li__K)((&__string_88)->li__LB.li__BC + 1) + (__li__K)(li__D3B->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__2CX),(&__string_88));
    li__45D(((__li__FC *)li__2CX),li__D3B);
    li__O3B=li__2GE(((__li__FC *)li__2CX),(&__string_4));
    li__MMI(((__li__FC *)li__O3B));
  };
  li__T3B=((__li__RB )(fopen((char*)(li__D3B->li__LB.li__CC),"wb")));
  li__U3B=(__li__K)(((__li__FC *)li__E3B)->li__GC.li__BC + 1);
  li__W3B=((__li__K )(fwrite((void *)((li__E3B->li__GC.li__CC)),(size_t)(1), (size_t)((li__U3B)),(FILE*)((li__T3B)))));
  if (((__li__2B *)li__2B__)->li__WC) {
    li__2CX=li__MPB();
    li__IZF=((__li__11C )li__W3B);
    if (li__IZF == ((__li__11C )(0x8000000000000000LLU))) {
      li__M4D(((__li__FC *)li__2CX),(&__string_89));
    } else /* FALSE */ {
      li__JAJ=0LL;
      li__MAJ=0;
      li__NAJ=0;
      if (0 == li__IZF) {
        li__DEE(((__li__FC *)li__2CX),'0');
      } else /* FALSE */ {
        if (li__IZF > 0LL) {
          li__JAJ=li__IZF;
        } else /* FALSE */ {
          li__JAJ=(__li__11C)(- li__IZF);
          li__DEE(((__li__FC *)li__2CX),'-');
        };
        li__MAJ=(__li__K)(li__2CX->li__GC.li__BC + 1);
        while ((li__JAJ != 0)) {
          li__51M=(__li__11C)(li__JAJ % 10LL);
          li__Z4M=((__li__X1C )li__51M);
          li__NXL=((__li__X1C )'0');
          li__DEE(((__li__FC *)li__2CX),((__li__MB )(((__li__X1C)(li__Z4M + li__NXL)))));
          li__JAJ=(__li__11C)(li__JAJ / 10LL);
        };
        li__NAJ=li__2CX->li__GC.li__BC;
        while ((li__MAJ < li__NAJ)) {
          li__VMP=((__li__FC *)li__2CX);
          li__INP=((__li__MB *)li__VMP->li__GC.li__CC)[li__MAJ];
          li__JNP=((__li__MB *)li__VMP->li__GC.li__CC)[li__NAJ];
          ((__li__MB *)li__VMP->li__GC.li__CC)[li__MAJ]=li__JNP;
          ((__li__MB *)li__VMP->li__GC.li__CC)[li__NAJ]=li__INP;
          li__NAJ=(__li__K)(li__NAJ - 1);
          li__MAJ=(__li__K)(li__MAJ + 1);
        };
      };
    };
    li__AUE=li__12D(((__li__FC *)li__2CX));
    li__EQB(&(li__AEB),li__2CX);
    li__2CX=li__GJB((__li__K)((__li__K)((&__string_90)->li__LB.li__BC + 1) + (__li__K)(((__li__FB *)li__AUE)->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__2CX),(&__string_90));
    li__45D(((__li__FC *)li__2CX),li__AUE);
    li__O3B=li__2GE(((__li__FC *)li__2CX),(&__string_91));
    li__MMI(((__li__FC *)li__O3B));
  };
  fclose((FILE*)((li__T3B)));
  if (((__li__2B *)li__2B__)->li__WC) {
    li__2CX=li__GJB((__li__K)((__li__K)((&__string_92)->li__LB.li__BC + 1) + (__li__K)(li__D3B->li__LB.li__BC + 1)));
    li__M4D(((__li__FC *)li__2CX),(&__string_92));
    li__45D(((__li__FC *)li__2CX),li__D3B);
    li__O3B=li__2GE(((__li__FC *)li__2CX),(&__string_4));
    li__MMI(((__li__FC *)li__O3B));
  };
}

static void li__0DP(__li__FC *li__1DP,__li__FC *li__2DP,__li__K li__3DP)
/* (Strict STRING_BUFFER{li__FC},Strict STRING_BUFFER{NULLxli__FC},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__4DP,li__PEP;
 li__4DP=li__1DP->li__GC.li__BC;
  li__PEP=(__li__K)(((__li__FC *)li__2DP)->li__GC.li__BC + 1);
  li__5PP(li__1DP,(__li__K)((__li__K)(li__4DP + li__PEP) + 1));
  if (li__3DP <= li__4DP) {
    li__2CR(((__li__MB *)li__1DP->li__GC.li__CC),li__3DP,li__4DP,li__PEP);
  };
  li__UZE(((__li__MB *)li__1DP->li__GC.li__CC),li__2DP->li__GC.li__CC,li__3DP,li__PEP);
}

static __li__K li__KZC(__li__FC *li__MZC)
/* (Strict STRING_BUFFER{NULLxli__FC}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__YZC,li__OZC;
 if (((__li__2B *)li__2B__)->li__WC) {
    li__MMI(((__li__FC *)li__MZC));
  };
  fflush(stdout);
  li__YZC=li__CHD(li__MZC,li__B__);
  if (((__li__2B *)li__2B__)->li__WC && (li__YZC != 0)) {
    li__41((&__string_77));
    li__PQF(li__YZC);
  };
  if (li__YZC != 0) {
    exit((li__YZC));
  };
  li__OZC=li__YZC;
  return(li__OZC);
}

static void li__UAC(__li__FC *li__VAC,__li__K li__WAC)
/* (Strict STRING_BUFFER{li__FC},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__MB *li__LBC;
 if (li__WAC > 0) {
    if (li__VAC->li__12 < li__WAC) {
      li__LBC=li__HHG(li__WAC);
      li__VAC->li__GC.li__CC=li__LBC;
      li__VAC->li__12=li__WAC;
    };
  };
  li__VAC->li__GC.li__BC=(__li__K)(- 1);
}

static __li__MB* li__HHG(__li__K li__JHG)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__VHG,li__ZSH;
  __li__MB *li__PSG;
  __li__MB *li__KHG;
 li__PSG=((__li__MB *)((__li__RB )(malloc((li__JHG)))));
  li__VHG=(__li__K)(li__JHG - 1);
  li__ZSH=li__VHG;
  while ((li__ZSH >= 0)) {
    li__PSG[li__ZSH]='\0';
    li__ZSH=(__li__K)(li__ZSH - 1);
  };
  li__KHG=li__PSG;
  return(li__KHG);
}

static void li__IWG(__li__MB *li__JWG,__li__K li__KWG,__li__K li__LWG)
/* (Strict NATIVE_ARRAY(Expanded CHARACTER){li__VB},Expanded INTEGER{li__K},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__SUH;
 li__SUH=li__KWG;
  while ((li__SUH <= li__LWG)) {
    li__JWG[li__SUH]='\0';
    li__SUH=(__li__K)(li__SUH + 1);
  };
}

static __li__FB* li__LZF(__li__FC *li__MZF)
/* (Strict STRING_BUFFER{li__FC}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__FB *li__QZF,*li__GKH,*li__CMH,*li__NZF;
  __li__RB li__HKH;
  __li__C1C li__YKH;
  __li__FB *li__TLH;
  __li__K li__OZF,li__FMH;
  __li__MB *li__1ZF;
 li__QZF=(__li__FB *)NULL;
  li__OZF=li__MZF->li__GC.li__BC;
  if (li__OZF > (__li__K)(- 1)) {
    li__1ZF=li__HHG((__li__K)(li__OZF + 2));
    li__GVF(li__1ZF,li__MZF->li__GC.li__CC,li__OZF);
    li__1ZF[(__li__K)(li__OZF + 1)]='\0';
    li__GKH=(__li__FB *)NULL;
    li__HKH=((__li__RB )(NULL));
    li__YKH=((__li__C1C )sizeof(__li__FB));
    if (0 == li__YKH) {
      li__GKH=li__FB__;
    } else /* FALSE */ {
      li__HKH=((__li__RB )(malloc(((li__YKH) + 3) & ~3)));
      li__Z2C=(__li__C1C)(li__Z2C - (__li__C1C)(((__li__C1C )0) - li__YKH));
      li__22C=(__li__C1C)(li__22C - (__li__C1C)(((__li__C1C )0) - li__YKH));
      li__TLH=((__li__FB *)li__HKH);
      li__GKH=li__TLH;
      *(li__TLH) = *(li__FB__);
    };
    li__CMH=((__li__FB *)li__GKH);
    li__CMH->li__LB.li__CC=li__1ZF;
    li__CMH->li__LB.li__BC=li__OZF;
    li__FMH=li__SWH(li__CMH);
    li__CMH->li__GXE=li__FMH;
    li__QZF=li__GKH;
  } else /* FALSE */ {
    li__QZF=(&__string_54);
  };
  li__NZF=li__QZF;
  return(li__NZF);
}

static void li__K0F(__li__FB *li__M0F)
/* (Generic Strict STRING_ALIAS{NULLxli__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__RB li__I3I;
  __li__C1C li__Z3I;
  __li__K li__N0F,li__O0F,li__S2G,li__S5H,li__41F;
  __li__3VE *li__P0F,*li__Q0F,*li__H3I,*li__POG;
  void **li__R0F;
  void **li__2NH;
  __li__3VE *li__U4I;
 li__N0F=0;
  li__O0F=0;
  li__P0F=(__li__3VE *)NULL;
  li__Q0F=(__li__3VE *)NULL;
  li__R0F=(void **)NULL;
  if (li__CWE == li__T0F) {
    li__O0F=(__li__K)(li__CWE - 1);
    li__R0F=li__UWE;
    li__N0F=li__30F;
    li__CWE=((__li__K )(hash_table[(li__N0F)]));
    li__2NH=((void **)((__li__RB )(malloc(((__li__K)(li__CWE * ((__li__K )(sizeof(void *)))))))));
    li__S2G=(__li__K)(li__CWE - 1);
    li__S5H=li__S2G;
    while ((li__S5H >= 0)) {
      li__2NH[li__S5H]=NULL;
      li__S5H=(__li__K)(li__S5H - 1);
    };
    li__UWE=li__2NH;
    li__30F=(__li__K)(li__30F + 1);
    while ((! (li__O0F < 0))) {
      li__P0F=(__li__3VE *)((void **)li__R0F)[li__O0F];
      while (((void *)li__P0F != (void *)NULL)) {
        li__Q0F=li__P0F->li__0XE;
        li__41F=(__li__K)(li__P0F->li__DXE->li__GXE % li__CWE);
        li__N0F=li__41F;
        if (li__41F < 0) {
          li__41((&__string_93));
          print_char('\n');
          li__PQF(li__P0F->li__DXE->li__GXE);
          printf("%p\n",(void*)(((__li__FB *)li__P0F->li__DXE)->li__LB.li__CC));
          li__N0F=0;
        };
        ((__li__3VE *)li__P0F)->li__0XE=(__li__3VE *)((void **)li__UWE)[li__N0F];
        ((void **)li__UWE)[li__N0F]=li__P0F;
        li__P0F=li__Q0F;
      };
      li__O0F=(__li__K)(li__O0F - 1);
    };
  };
  li__O0F=(__li__K)(li__M0F->li__GXE % li__CWE);
  li__N0F=li__O0F;
  li__Q0F=(__li__3VE *)((void **)li__UWE)[li__O0F];
  li__H3I=(__li__3VE *)NULL;
  li__I3I=((__li__RB )(NULL));
  li__Z3I=((__li__C1C )sizeof(__li__3VE));
  if (0 == li__Z3I) {
    li__H3I=(__li__3VE *)li__3VE__;
  } else /* FALSE */ {
    li__I3I=((__li__RB )(malloc(((li__Z3I) + 3) & ~3)));
    li__Z2C=(__li__C1C)(li__Z2C - (__li__C1C)(((__li__C1C )0) - li__Z3I));
    li__22C=(__li__C1C)(li__22C - (__li__C1C)(((__li__C1C )0) - li__Z3I));
    li__U4I=((__li__3VE *)li__I3I);
    li__H3I=li__U4I;
    *(li__U4I) = *(li__3VE__);
  };
  li__POG=((__li__3VE *)li__H3I);
  li__POG->li__DXE=li__M0F;
  li__POG->li__0XE=li__Q0F;
  li__P0F=li__H3I;
  ((void **)li__UWE)[li__O0F]=li__H3I;
  li__T0F=(__li__K)(li__T0F + 1);
}

static __li__K li__JPG(__li__K li__KPG)
/* (Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__NPG,li__MPG;
 li__NPG=0;
  if (li__KPG > 32) {
    li__NPG=32;
  } else /* FALSE */ {
    li__NPG=li__KPG;
  };
  li__MPG=li__NPG;
  return(li__MPG);
}

static void li__DEE(__li__FC *li__EEE,__li__MB li__FEE)
/* (Strict STRING_BUFFER{li__FC},Expanded CHARACTER{li__MB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__3EE,li__0DX;
  __li__MB *li__VEE;
  __li__MB *li__ZDX;
 if (li__EEE->li__12 == (__li__K)(li__EEE->li__GC.li__BC + 1)) {
    if (0 == li__EEE->li__12) {
      li__EEE->li__12=32;
      li__VEE=li__HHG(32);
      li__EEE->li__GC.li__CC=li__VEE;
    } else /* FALSE */ {
      li__3EE=(__li__K)(li__EEE->li__12 << 1);
      li__VEE=((__li__MB *)li__EEE->li__GC.li__CC);
      li__0DX=li__EEE->li__12;
      li__ZDX=((__li__MB *)((__li__RB )(realloc((((__li__RB )li__VEE)),(li__3EE)))));
      li__IWG(li__ZDX,li__0DX,(__li__K)(li__3EE - 1));
      li__EEE->li__GC.li__CC=li__ZDX;
      li__EEE->li__12=li__3EE;
    };
  };
  li__EEE->li__GC.li__BC=(__li__K)(li__EEE->li__GC.li__BC + 1);
  ((__li__MB *)li__EEE->li__GC.li__CC)[li__EEE->li__GC.li__BC]=li__FEE;
  ;
}

static void li__UZE(__li__MB *li__VZE,__li__MB *li__WZE,__li__K li__XZE,__li__K li__YZE)
/* (Strict NATIVE_ARRAY(Expanded CHARACTER){li__VB},Strict NATIVE_ARRAY(Expanded CHARACTER){NULLxli__VB},Expanded INTEGER{li__K},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__J0E,li__I0E;
 li__J0E=0;
  li__I0E=li__XZE;
  while ((li__J0E != li__YZE)) {
    li__VZE[li__I0E]=((__li__MB *)li__WZE)[li__J0E];
    li__J0E=(__li__K)(li__J0E + 1);
    li__I0E=(__li__K)(li__I0E + 1);
  };
}

static void li__GVF(__li__MB *li__HVF,__li__MB *li__IVF,__li__K li__JVF)
/* (Strict NATIVE_ARRAY(Expanded CHARACTER){li__VB},Strict NATIVE_ARRAY(Expanded CHARACTER){NULLxli__VB},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__NKG;
 li__NKG=0;
  while ((li__NKG <= li__JVF)) {
    li__HVF[li__NKG]=((__li__MB *)li__IVF)[li__NKG];
    li__NKG=(__li__K)(li__NKG + 1);
  };
}

static __li__K li__CHD(__li__FC *li__EHD,__li__C li__FHD)
/* (Strict STRING_BUFFER{NULLxli__FC},Expanded BOOLEAN{li__Bxli__I}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__HHD,li__OZD,li__GHD;
  __li__MB *li__HZD;
 li__HHD=0;
  if (li__FHD) {
    li__HZD=li__BCE(((__li__FC *)li__EHD));
    run_background((li__HZD));
  } else /* FALSE */ {
    li__HZD=li__BCE(((__li__FC *)li__EHD));
    {;
    li__OZD=((__li__K )(system((char*)((li__HZD)))));
    };
    li__HHD=((__li__K )(WEXITSTATUS((li__OZD))));
  };
  li__GHD=li__HHD;
  return(li__GHD);
}

static void li__PQF(__li__K li__QQF)
/* (Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__C li__BYF;
 if (0 == li__QQF) {
    print_char('0');
    li__BYF=li__B__;
  } else /* FALSE */ {
    li__BYF=li__I__;
  };
  if (! li__BYF) {
    if (li__QQF < 0) {
      print_char('-');
      li__YZJ((__li__K)(- li__QQF));
    } else /* FALSE */ {
      li__YZJ(li__QQF);
    };
  };
  print_char('\n');
}

static __li__C li__RFC(void *li__TFC)
/* (STRING{li__FB}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__RB li__YFC;
  __li__C li__VFC,li__UFC;
 li__VFC=li__I__;
  li__YFC=li__ADC(li__TFC);
  if (li__YFC != (void *)NULL) {
    li__VFC=li__B__;
    fclose((FILE*)((li__YFC)));
  };
  li__UFC=li__VFC;
  return(li__UFC);
}

static void li__IRC(__li__FC *li__KRC,__li__FB *li__LRC)
/* (Strict STRING_BUFFER{NULLxli__FC},Strict STRING_ALIAS{NULLxli__FB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__FC *li__ORF,*li__HHP;
  __li__MB li__1RF;
  __li__C li__ORC;
 li__M4D(((__li__FC *)li__KRC),li__LRC);
  li__ORF=((__li__FC *)li__KRC);
  li__1RF=((__li__MB *)li__ORF->li__GC.li__CC)[li__ORF->li__GC.li__BC];
  li__ORC=li__QK((&__string_94),li__1RF);
  if (li__ORC) {
    li__HHP=((__li__FC *)li__KRC);
    if (1 > li__HHP->li__GC.li__BC) {
      li__HHP->li__GC.li__BC=(__li__K)(- 1);
    } else /* FALSE */ {
      li__HHP->li__GC.li__BC=(__li__K)(li__HHP->li__GC.li__BC - 1);
    };
    ;
  };
  li__M4D(((__li__FC *)li__KRC),(&__string_95));
}

static __li__K li__XTP(__li__FC *li__YTP,void *li__ZTP)
/* (Strict STRING_BUFFER{li__FC},STRING{li__FB}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__GB *li__PEX,*li__QEX,*li__REX,*li__SEX,*li__TEX,*li__UEX;
  __li__K li__2TP,li__4TP,li__3TP,li__HEX,li__1TP;
  __li__C li__DWP;
  __li__MB li__5VP;
 li__2TP=0;
  li__4TP=(__li__K)(- 1);
  li__3TP=0;
  li__PEX=&(((__li__FB *)li__ZTP)->li__LB);
  li__QEX=&(li__YTP->li__GC);
  li__REX=&(((__li__FB *)li__ZTP)->li__LB);
  li__SEX=&(li__YTP->li__GC);
  li__TEX=&(((__li__FB *)li__ZTP)->li__LB);
  li__UEX=&(((__li__FB *)li__ZTP)->li__LB);
  while ((! ((li__4TP != (__li__K)(- 1)) || ((__li__K)(li__3TP + li__PEX->li__BC) > li__QEX->li__BC)))) {
    li__2TP=0;
    li__PZS:
    {
      if (li__2TP > li__REX->li__BC) {
        li__DWP=li__B__;
      } else /* FALSE */ {
        li__HEX=(__li__K)(li__3TP + li__2TP);
        li__5VP=((__li__MB *)li__SEX->li__CC)[li__HEX];
        li__DWP=(li__5VP != ((__li__MB *)li__TEX->li__CC)[li__2TP]);
      };
      if (! li__DWP) {
        li__2TP=(__li__K)(li__2TP + 1);
        goto li__PZS;
      };
    };
    if (li__2TP > li__UEX->li__BC) {
      li__4TP=li__3TP;
    } else /* FALSE */ {
      li__3TP=(__li__K)(li__3TP + 1);
    };
  };
  li__1TP=li__4TP;
  return(li__1TP);
}

static void li__KHP(__li__FC *li__LHP,__li__FC *li__MHP)
/* (Strict STRING_BUFFER{li__FC},Strict STRING_BUFFER{NULLxli__FC}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__VHP,li__XHP,li__EEX;
  __li__MB *li__GIP;
  __li__MB *li__DEX;
 li__VHP=(__li__K)(((__li__FC *)li__MHP)->li__GC.li__BC + 1);
  li__XHP=(__li__K)((__li__K)(li__LHP->li__GC.li__BC + 1) + li__VHP);
  if (li__LHP->li__12 < li__XHP) {
    if (0 == li__LHP->li__12) {
      li__LHP->li__12=li__XHP;
      li__GIP=li__HHG(li__XHP);
      li__LHP->li__GC.li__CC=li__GIP;
    } else /* FALSE */ {
      li__GIP=((__li__MB *)li__LHP->li__GC.li__CC);
      li__EEX=li__LHP->li__12;
      li__DEX=((__li__MB *)((__li__RB )(realloc((((__li__RB )li__GIP)),(li__XHP)))));
      li__IWG(li__DEX,li__EEX,(__li__K)(li__XHP - 1));
      li__LHP->li__GC.li__CC=li__DEX;
      li__LHP->li__12=li__XHP;
    };
  };
  li__UZE(((__li__MB *)li__LHP->li__GC.li__CC),li__MHP->li__GC.li__CC,(__li__K)(li__LHP->li__GC.li__BC + 1),li__VHP);
  li__LHP->li__GC.li__BC=(__li__K)(li__XHP - 1);
}

static void li__5PP(__li__FC *li__AQP,__li__K li__BQP)
/* (Strict STRING_BUFFER{li__FC},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__YEX;
  __li__MB *li__FRP;
  __li__MB *li__XEX;
 if (! (li__BQP <= (__li__K)(li__AQP->li__GC.li__BC + 1))) {
    if (li__AQP->li__12 < li__BQP) {
      if (0 == li__AQP->li__12) {
        li__FRP=li__HHG(li__BQP);
        li__AQP->li__GC.li__CC=li__FRP;
      } else /* FALSE */ {
        li__FRP=((__li__MB *)li__AQP->li__GC.li__CC);
        li__YEX=li__AQP->li__12;
        li__XEX=((__li__MB *)((__li__RB )(realloc((((__li__RB )li__FRP)),(li__BQP)))));
        li__IWG(li__XEX,li__YEX,(__li__K)(li__BQP - 1));
        li__AQP->li__GC.li__CC=li__XEX;
      };
      li__AQP->li__12=li__BQP;
    } else /* FALSE */ {
      li__IWG(((__li__MB *)li__AQP->li__GC.li__CC),(__li__K)(li__AQP->li__GC.li__BC + 1),(__li__K)(li__BQP - 1));
    };
  };
  li__AQP->li__GC.li__BC=(__li__K)(li__BQP - 1);
  ;
}

static void li__2CR(__li__MB *li__3CR,__li__K li__4CR,__li__K li__5CR,__li__K li__ADR)
/* (Strict NATIVE_ARRAY(Expanded CHARACTER){li__VB},Expanded INTEGER{li__K},Expanded INTEGER{li__K},Expanded INTEGER{li__K}) Void No recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__CLS;
 if (li__ADR != 0) {
    if (li__ADR < 0) {
      li__CLS=li__4CR;
      while ((li__CLS <= li__5CR)) {
        li__3CR[(__li__K)(li__CLS + li__ADR)]=li__3CR[li__CLS];
        li__CLS=(__li__K)(li__CLS + 1);
      };
    } else /* FALSE */ {
      li__CLS=li__5CR;
      while ((li__CLS >= li__4CR)) {
        li__3CR[(__li__K)(li__CLS + li__ADR)]=li__3CR[li__CLS];
        li__CLS=(__li__K)(li__CLS - 1);
      };
    };
  };
}

static __li__K li__SWH(__li__FB *li__TWH)
/* (Strict STRING_ALIAS{li__FB}) With result No recursive, No inlinable. NO CONTEXT! */
{
   __li__GB *li__3EX;
  __li__K li__VWH,li__YWH,li__TDI,li__4WH,li__UWH;
 li__VWH=0;
  li__YWH=li__JPG(li__TWH->li__LB.li__BC);
  li__TDI=0;
  li__3EX=&(li__TWH->li__LB);
  while ((li__TDI <= li__YWH)) {
    li__4WH=(__li__K)(li__VWH << 2);
    li__VWH=(__li__K)(li__4WH + ((__li__K )((__li__X1C )((__li__MB *)li__3EX->li__CC)[li__TDI])));
    li__TDI=(__li__K)(li__TDI + 1);
  };
  li__UWH=(__li__K)(li__VWH & 2147483647);
  return(li__UWH);
}

static void li__YZJ(__li__K li__ZZJ)
/* (Expanded INTEGER{li__K}) Void Recursive, No inlinable. NO CONTEXT! */
{
   __li__K li__D0J;
  __li__X1C li__XVK,li__BSW;
  __li__MB li__1VK;
 li__D0J=(__li__K)(li__ZZJ % 10);
  li__XVK=((__li__X1C )li__D0J);
  li__BSW=((__li__X1C )'0');
  li__1VK=((__li__MB )(((__li__X1C)(li__XVK + li__BSW))));
  li__D0J=(__li__K)(li__ZZJ / 10);
  if (li__D0J != 0) {
    li__YZJ(li__D0J);
  };
  print_char(li__1VK);
}
static void init_string_alias() {
  if (__string_1.li__GXE!=li__SWH(&__string_1)) { print_string("ERROR[Installing Lisaac Ω Compiler and Tools.]\n"); };
  __string_1.li__GXE = li__SWH(&__string_1);
  li__K0F(&__string_1);
  if (__string_2.li__GXE!=li__SWH(&__string_2)) { print_string("ERROR[--verbose]\n"); };
  __string_2.li__GXE = li__SWH(&__string_2);
  li__K0F(&__string_2);
  if (__string_3.li__GXE!=li__SWH(&__string_3)) { print_string("ERROR[Unknow option \"]\n"); };
  __string_3.li__GXE = li__SWH(&__string_3);
  li__K0F(&__string_3);
  if (__string_4.li__GXE!=li__SWH(&__string_4)) { print_string("ERROR[\".]\n"); };
  __string_4.li__GXE = li__SWH(&__string_4);
  li__K0F(&__string_4);
  if (__string_5.li__GXE!=li__SWH(&__string_5)) { print_string("ERROR[Usage: build_lisaac [--verbose]]\n"); };
  __string_5.li__GXE = li__SWH(&__string_5);
  li__K0F(&__string_5);
  if (__string_6.li__GXE!=li__SWH(&__string_6)) { print_string("ERROR[Running from \"]\n"); };
  __string_6.li__GXE = li__SWH(&__string_6);
  li__K0F(&__string_6);
  if (__string_7.li__GXE!=li__SWH(&__string_7)) { print_string("ERROR[windows]\n"); };
  __string_7.li__GXE = li__SWH(&__string_7);
  li__K0F(&__string_7);
  if (__string_8.li__GXE!=li__SWH(&__string_8)) { print_string("ERROR[android]\n"); };
  __string_8.li__GXE = li__SWH(&__string_8);
  li__K0F(&__string_8);
  if (__string_9.li__GXE!=li__SWH(&__string_9)) { print_string("ERROR[apple]\n"); };
  __string_9.li__GXE = li__SWH(&__string_9);
  li__K0F(&__string_9);
  if (__string_10.li__GXE!=li__SWH(&__string_10)) { print_string("ERROR[unix]\n"); };
  __string_10.li__GXE = li__SWH(&__string_10);
  li__K0F(&__string_10);
  if (__string_11.li__GXE!=li__SWH(&__string_11)) { print_string("ERROR[Warning: strange system name \"]\n"); };
  __string_11.li__GXE = li__SWH(&__string_11);
  li__K0F(&__string_11);
  if (__string_12.li__GXE!=li__SWH(&__string_12)) { print_string("ERROR[\".\n]\n"); };
  __string_12.li__GXE = li__SWH(&__string_12);
  li__K0F(&__string_12);
  if (__string_13.li__GXE!=li__SWH(&__string_13)) { print_string("ERROR[system=\"]\n"); };
  __string_13.li__GXE = li__SWH(&__string_13);
  li__K0F(&__string_13);
  if (__string_14.li__GXE!=li__SWH(&__string_14)) { print_string("ERROR[Warning: Warning: Avoid spaces in the Lisaac Ω path.\n]\n"); };
  __string_14.li__GXE = li__SWH(&__string_14);
  li__K0F(&__string_14);
  if (__string_15.li__GXE!=li__SWH(&__string_15)) { print_string("ERROR[lisaac_dir=\"]\n"); };
  __string_15.li__GXE = li__SWH(&__string_15);
  li__K0F(&__string_15);
  if (__string_16.li__GXE!=li__SWH(&__string_16)) { print_string("ERROR[lisaac/]\n"); };
  __string_16.li__GXE = li__SWH(&__string_16);
  li__K0F(&__string_16);
  if (__string_17.li__GXE!=li__SWH(&__string_17)) { print_string("ERROR[buid_lisaac must be run from lisaac directory.]\n"); };
  __string_17.li__GXE = li__SWH(&__string_17);
  li__K0F(&__string_17);
  if (__string_18.li__GXE!=li__SWH(&__string_18)) { print_string("ERROR[bin]\n"); };
  __string_18.li__GXE = li__SWH(&__string_18);
  li__K0F(&__string_18);
  if (__string_19.li__GXE!=li__SWH(&__string_19)) { print_string("ERROR[lisaac_bin_dir=\"]\n"); };
  __string_19.li__GXE = li__SWH(&__string_19);
  li__K0F(&__string_19);
  if (__string_20.li__GXE!=li__SWH(&__string_20)) { print_string("ERROR[elix]\n"); };
  __string_20.li__GXE = li__SWH(&__string_20);
  li__K0F(&__string_20);
  if (__string_21.li__GXE!=li__SWH(&__string_21)) { print_string("ERROR[elix_dir=\"]\n"); };
  __string_21.li__GXE = li__SWH(&__string_21);
  li__K0F(&__string_21);
  if (__string_22.li__GXE!=li__SWH(&__string_22)) { print_string("ERROR[HOME]\n"); };
  __string_22.li__GXE = li__SWH(&__string_22);
  li__K0F(&__string_22);
  if (__string_23.li__GXE!=li__SWH(&__string_23)) { print_string("ERROR[Warning: No $HOME variable.]\n"); };
  __string_23.li__GXE = li__SWH(&__string_23);
  li__K0F(&__string_23);
  if (__string_24.li__GXE!=li__SWH(&__string_24)) { print_string("ERROR[user_homedir=\"]\n"); };
  __string_24.li__GXE = li__SWH(&__string_24);
  li__K0F(&__string_24);
  if (__string_25.li__GXE!=li__SWH(&__string_25)) { print_string("ERROR[.elix.cfg]\n"); };
  __string_25.li__GXE = li__SWH(&__string_25);
  li__K0F(&__string_25);
  if (__string_26.li__GXE!=li__SWH(&__string_26)) { print_string("ERROR[Remove old \"]\n"); };
  __string_26.li__GXE = li__SWH(&__string_26);
  li__K0F(&__string_26);
  if (__string_27.li__GXE!=li__SWH(&__string_27)) { print_string("ERROR[Cannot remove \"]\n"); };
  __string_27.li__GXE = li__SWH(&__string_27);
  li__K0F(&__string_27);
  if (__string_28.li__GXE!=li__SWH(&__string_28)) { print_string("ERROR[SHELL]\n"); };
  __string_28.li__GXE = li__SWH(&__string_28);
  li__K0F(&__string_28);
  if (__string_29.li__GXE!=li__SWH(&__string_29)) { print_string("ERROR[No $SHELL variable.]\n"); };
  __string_29.li__GXE = li__SWH(&__string_29);
  li__K0F(&__string_29);
  if (__string_30.li__GXE!=li__SWH(&__string_30)) { print_string("ERROR[/usr/bin/bash]\n"); };
  __string_30.li__GXE = li__SWH(&__string_30);
  li__K0F(&__string_30);
  if (__string_31.li__GXE!=li__SWH(&__string_31)) { print_string("ERROR[/bin/bash]\n"); };
  __string_31.li__GXE = li__SWH(&__string_31);
  li__K0F(&__string_31);
  if (__string_32.li__GXE!=li__SWH(&__string_32)) { print_string("ERROR[shell=\"]\n"); };
  __string_32.li__GXE = li__SWH(&__string_32);
  li__K0F(&__string_32);
  if (__string_33.li__GXE!=li__SWH(&__string_33)) { print_string("ERROR[C compiling lisaac/bin/lisaac.c ... wait...]\n"); };
  __string_33.li__GXE = li__SWH(&__string_33);
  li__K0F(&__string_33);
  if (__string_34.li__GXE!=li__SWH(&__string_34)) { print_string("ERROR[gcc lisaac.c -o lisaac -O2]\n"); };
  __string_34.li__GXE = li__SWH(&__string_34);
  li__K0F(&__string_34);
  if (__string_35.li__GXE!=li__SWH(&__string_35)) { print_string("ERROR[.bashrc]\n"); };
  __string_35.li__GXE = li__SWH(&__string_35);
  li__K0F(&__string_35);
  if (__string_36.li__GXE!=li__SWH(&__string_36)) { print_string("ERROR[/bin/zsh]\n"); };
  __string_36.li__GXE = li__SWH(&__string_36);
  li__K0F(&__string_36);
  if (__string_37.li__GXE!=li__SWH(&__string_37)) { print_string("ERROR[.zshrc]\n"); };
  __string_37.li__GXE = li__SWH(&__string_37);
  li__K0F(&__string_37);
  if (__string_38.li__GXE!=li__SWH(&__string_38)) { print_string("ERROR[.cshrc]\n"); };
  __string_38.li__GXE = li__SWH(&__string_38);
  li__K0F(&__string_38);
  if (__string_39.li__GXE!=li__SWH(&__string_39)) { print_string("ERROR[No rc_file.]\n"); };
  __string_39.li__GXE = li__SWH(&__string_39);
  li__K0F(&__string_39);
  if (__string_40.li__GXE!=li__SWH(&__string_40)) { print_string("ERROR[Update lisaac/make.lip config.]\n"); };
  __string_40.li__GXE = li__SWH(&__string_40);
  li__K0F(&__string_40);
  if (__string_41.li__GXE!=li__SWH(&__string_41)) { print_string("ERROR[make.lip]\n"); };
  __string_41.li__GXE = li__SWH(&__string_41);
  li__K0F(&__string_41);
  if (__string_42.li__GXE!=li__SWH(&__string_42)) { print_string("ERROR[Cannot read make.lip.]\n"); };
  __string_42.li__GXE = li__SWH(&__string_42);
  li__K0F(&__string_42);
  if (__string_43.li__GXE!=li__SWH(&__string_43)) { print_string("ERROR[+ target:STRING := \"]\n"); };
  __string_43.li__GXE = li__SWH(&__string_43);
  li__K0F(&__string_43);
  if (__string_44.li__GXE!=li__SWH(&__string_44)) { print_string("ERROR[Update lisaac/elix/assets/elix.cfg.]\n"); };
  __string_44.li__GXE = li__SWH(&__string_44);
  li__K0F(&__string_44);
  if (__string_45.li__GXE!=li__SWH(&__string_45)) { print_string("ERROR[assets]\n"); };
  __string_45.li__GXE = li__SWH(&__string_45);
  li__K0F(&__string_45);
  if (__string_46.li__GXE!=li__SWH(&__string_46)) { print_string("ERROR[elix.cfg]\n"); };
  __string_46.li__GXE = li__SWH(&__string_46);
  li__K0F(&__string_46);
  if (__string_47.li__GXE!=li__SWH(&__string_47)) { print_string("ERROR[Cannot read lisaac/elix/assets/elix.cfg.]\n"); };
  __string_47.li__GXE = li__SWH(&__string_47);
  li__K0F(&__string_47);
  if (__string_48.li__GXE!=li__SWH(&__string_48)) { print_string("ERROR[shortcut   : \"]\n"); };
  __string_48.li__GXE = li__SWH(&__string_48);
  li__K0F(&__string_48);
  if (__string_49.li__GXE!=li__SWH(&__string_49)) { print_string("ERROR[standard]\n"); };
  __string_49.li__GXE = li__SWH(&__string_49);
  li__K0F(&__string_49);
  if (__string_50.li__GXE!=li__SWH(&__string_50)) { print_string("ERROR[mac_os]\n"); };
  __string_50.li__GXE = li__SWH(&__string_50);
  li__K0F(&__string_50);
  if (__string_51.li__GXE!=li__SWH(&__string_51)) { print_string("ERROR[decorated  : ]\n"); };
  __string_51.li__GXE = li__SWH(&__string_51);
  li__K0F(&__string_51);
  if (__string_52.li__GXE!=li__SWH(&__string_52)) { print_string("ERROR[false]\n"); };
  __string_52.li__GXE = li__SWH(&__string_52);
  li__K0F(&__string_52);
  if (__string_53.li__GXE!=li__SWH(&__string_53)) { print_string("ERROR[true]\n"); };
  __string_53.li__GXE = li__SWH(&__string_53);
  li__K0F(&__string_53);
  if (__string_54.li__GXE!=li__SWH(&__string_54)) { print_string("ERROR[]\n"); };
  __string_54.li__GXE = li__SWH(&__string_54);
  li__K0F(&__string_54);
  if (__string_55.li__GXE!=li__SWH(&__string_55)) { print_string("ERROR[Update lisaac/misc/new_assets.sh.]\n"); };
  __string_55.li__GXE = li__SWH(&__string_55);
  li__K0F(&__string_55);
  if (__string_56.li__GXE!=li__SWH(&__string_56)) { print_string("ERROR[misc]\n"); };
  __string_56.li__GXE = li__SWH(&__string_56);
  li__K0F(&__string_56);
  if (__string_57.li__GXE!=li__SWH(&__string_57)) { print_string("ERROR[new_assets.sh]\n"); };
  __string_57.li__GXE = li__SWH(&__string_57);
  li__K0F(&__string_57);
  if (__string_58.li__GXE!=li__SWH(&__string_58)) { print_string("ERROR[Cannot read lisaac/elix/assets/new_assets.sh.]\n"); };
  __string_58.li__GXE = li__SWH(&__string_58);
  li__K0F(&__string_58);
  if (__string_59.li__GXE!=li__SWH(&__string_59)) { print_string("ERROR[#!]\n"); };
  __string_59.li__GXE = li__SWH(&__string_59);
  li__K0F(&__string_59);
  if (__string_60.li__GXE!=li__SWH(&__string_60)) { print_string("ERROR[lisaac/misc/new_assets.sh not updated.]\n"); };
  __string_60.li__GXE = li__SWH(&__string_60);
  li__K0F(&__string_60);
  if (__string_61.li__GXE!=li__SWH(&__string_61)) { print_string("ERROR[Compiling lisaac/elix ... wait...]\n"); };
  __string_61.li__GXE = li__SWH(&__string_61);
  li__K0F(&__string_61);
  if (__string_62.li__GXE!=li__SWH(&__string_62)) { print_string("ERROR[lisaac elix -q -boost]\n"); };
  __string_62.li__GXE = li__SWH(&__string_62);
  li__K0F(&__string_62);
  if (__string_63.li__GXE!=li__SWH(&__string_63)) { print_string("ERROR[Compiling lisaac/example/welcome.li ... wait...]\n"); };
  __string_63.li__GXE = li__SWH(&__string_63);
  li__K0F(&__string_63);
  if (__string_64.li__GXE!=li__SWH(&__string_64)) { print_string("ERROR[example]\n"); };
  __string_64.li__GXE = li__SWH(&__string_64);
  li__K0F(&__string_64);
  if (__string_65.li__GXE!=li__SWH(&__string_65)) { print_string("ERROR[welcome]\n"); };
  __string_65.li__GXE = li__SWH(&__string_65);
  li__K0F(&__string_65);
  if (__string_66.li__GXE!=li__SWH(&__string_66)) { print_string("ERROR[elix welcome.li]\n"); };
  __string_66.li__GXE = li__SWH(&__string_66);
  li__K0F(&__string_66);
  if (__string_67.li__GXE!=li__SWH(&__string_67)) { print_string("ERROR[lisaac welcome -q -boost]\n"); };
  __string_67.li__GXE = li__SWH(&__string_67);
  li__K0F(&__string_67);
  if (__string_68.li__GXE!=li__SWH(&__string_68)) { print_string("ERROR[example/welcome/welcome]\n"); };
  __string_68.li__GXE = li__SWH(&__string_68);
  li__K0F(&__string_68);
  if (__string_69.li__GXE!=li__SWH(&__string_69)) { print_string("ERROR[Installation Completed Successfully.]\n"); };
  __string_69.li__GXE = li__SWH(&__string_69);
  li__K0F(&__string_69);
  if (__string_70.li__GXE!=li__SWH(&__string_70)) { print_string("ERROR[Open a new terminal window.]\n"); };
  __string_70.li__GXE = li__SWH(&__string_70);
  li__K0F(&__string_70);
  if (__string_71.li__GXE!=li__SWH(&__string_71)) { print_string("ERROR[or:]\n"); };
  __string_71.li__GXE = li__SWH(&__string_71);
  li__K0F(&__string_71);
  if (__string_72.li__GXE!=li__SWH(&__string_72)) { print_string("ERROR[source ~/]\n"); };
  __string_72.li__GXE = li__SWH(&__string_72);
  li__K0F(&__string_72);
  if (__string_73.li__GXE!=li__SWH(&__string_73)) { print_string("ERROR[Rerun using --verbose to try to debug.]\n"); };
  __string_73.li__GXE = li__SWH(&__string_73);
  li__K0F(&__string_73);
  if (__string_74.li__GXE!=li__SWH(&__string_74)) { print_string("ERROR[cd \"]\n"); };
  __string_74.li__GXE = li__SWH(&__string_74);
  li__K0F(&__string_74);
  if (__string_75.li__GXE!=li__SWH(&__string_75)) { print_string("ERROR[\"]\n"); };
  __string_75.li__GXE = li__SWH(&__string_75);
  li__K0F(&__string_75);
  if (__string_76.li__GXE!=li__SWH(&__string_76)) { print_string("ERROR[Fail.]\n"); };
  __string_76.li__GXE = li__SWH(&__string_76);
  li__K0F(&__string_76);
  if (__string_77.li__GXE!=li__SWH(&__string_77)) { print_string("ERROR[exit status:]\n"); };
  __string_77.li__GXE = li__SWH(&__string_77);
  li__K0F(&__string_77);
  if (__string_78.li__GXE!=li__SWH(&__string_78)) { print_string("ERROR[Create/Update \"]\n"); };
  __string_78.li__GXE = li__SWH(&__string_78);
  li__K0F(&__string_78);
  if (__string_79.li__GXE!=li__SWH(&__string_79)) { print_string("ERROR[Checking export PATH for \"]\n"); };
  __string_79.li__GXE = li__SWH(&__string_79);
  li__K0F(&__string_79);
  if (__string_80.li__GXE!=li__SWH(&__string_80)) { print_string("ERROR[Creating \"]\n"); };
  __string_80.li__GXE = li__SWH(&__string_80);
  li__K0F(&__string_80);
  if (__string_81.li__GXE!=li__SWH(&__string_81)) { print_string("ERROR[export PATH=\"]\n"); };
  __string_81.li__GXE = li__SWH(&__string_81);
  li__K0F(&__string_81);
  if (__string_82.li__GXE!=li__SWH(&__string_82)) { print_string("ERROR[$PATH\"\n]\n"); };
  __string_82.li__GXE = li__SWH(&__string_82);
  li__K0F(&__string_82);
  if (__string_83.li__GXE!=li__SWH(&__string_83)) { print_string("ERROR[\n# **** LISAAC-OMEGA TOOLS ****\n]\n"); };
  __string_83.li__GXE = li__SWH(&__string_83);
  li__K0F(&__string_83);
  if (__string_84.li__GXE!=li__SWH(&__string_84)) { print_string("ERROR[Cannot read \"]\n"); };
  __string_84.li__GXE = li__SWH(&__string_84);
  li__K0F(&__string_84);
  if (__string_85.li__GXE!=li__SWH(&__string_85)) { print_string("ERROR[Tag \"]\n"); };
  __string_85.li__GXE = li__SWH(&__string_85);
  li__K0F(&__string_85);
  if (__string_86.li__GXE!=li__SWH(&__string_86)) { print_string("ERROR[\" not in ]\n"); };
  __string_86.li__GXE = li__SWH(&__string_86);
  li__K0F(&__string_86);
  if (__string_87.li__GXE!=li__SWH(&__string_87)) { print_string("ERROR[.]\n"); };
  __string_87.li__GXE = li__SWH(&__string_87);
  li__K0F(&__string_87);
  if (__string_88.li__GXE!=li__SWH(&__string_88)) { print_string("ERROR[Open write \"]\n"); };
  __string_88.li__GXE = li__SWH(&__string_88);
  li__K0F(&__string_88);
  if (__string_89.li__GXE!=li__SWH(&__string_89)) { print_string("ERROR[-9223372036854775808]\n"); };
  __string_89.li__GXE = li__SWH(&__string_89);
  li__K0F(&__string_89);
  if (__string_90.li__GXE!=li__SWH(&__string_90)) { print_string("ERROR[writen ]\n"); };
  __string_90.li__GXE = li__SWH(&__string_90);
  li__K0F(&__string_90);
  if (__string_91.li__GXE!=li__SWH(&__string_91)) { print_string("ERROR[ bytes.]\n"); };
  __string_91.li__GXE = li__SWH(&__string_91);
  li__K0F(&__string_91);
  if (__string_92.li__GXE!=li__SWH(&__string_92)) { print_string("ERROR[Close \"]\n"); };
  __string_92.li__GXE = li__SWH(&__string_92);
  li__K0F(&__string_92);
  if (__string_93.li__GXE!=li__SWH(&__string_93)) { print_string("ERROR[Crash ALIAS TO : hash code < 0]\n"); };
  __string_93.li__GXE = li__SWH(&__string_93);
  li__K0F(&__string_93);
  if (__string_94.li__GXE!=li__SWH(&__string_94)) { print_string("ERROR[/\\]\n"); };
  __string_94.li__GXE = li__SWH(&__string_94);
  li__K0F(&__string_94);
  if (__string_95.li__GXE!=li__SWH(&__string_95)) { print_string("ERROR[:]\n"); };
  __string_95.li__GXE = li__SWH(&__string_95);
  li__K0F(&__string_95);
};

/*==========================*/
/* DEBUG MANAGER            */
/*==========================*/

int print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
  return(0);
}

