/* C code generated by Lisaac compiler (www.lisaac.org) */

#define _LARGE_FILE_API
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
#include <signal.h>
int print_string(char *str);
int arg_count;
char **arg_vector;

/*==========================*/
/* EXTERNAL                 */
/*==========================*/

/* FLOAT_REAL */
#include <math.h>
/* SYSTEM_IO */

#include <stdio.h>
#include <stdlib.h>

/* Hardware 'print_char' */
void print_char(char);

/* Hardware 'exit' */
void die_with_code(int);

/* VIDEO */

#include <X11/Xlib.h>

// For Frame buffer.
//#include <X11/extensions/XTest.h>
//#include <linux/fb.h>
#include <string.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <errno.h>

Display *display;
Window  window;
GC      gc;
Screen  *screen;
XImage  *ximage=NULL;

/* SYSTEM */
#include <time.h>

/*==========================*/
/* TYPE                     */
/*==========================*/

/* Generic Object */
struct ___OBJ {
  unsigned int __id;
};

typedef struct li__BB_struct __li__AB; /* ALIAS with li__BB */
typedef struct li__BB_struct __li__BB;
/* NULL */
#ifndef NULL
#define NULL ((void *)0)
#endif

typedef signed int __li__I;
typedef char __li__JB;
/* li__BB */
#define __li__BB__ 0
struct li__BB_struct {
  __li__I li__GG;
  __li__JB *li__HG;
};
/* li__AB */
#define __li__AB__ 1
typedef char __li__C;
#define li__G__ 0
#define li__B__ 1
/* ___CONTEXT */
typedef struct ___CONTEXT_struct _____CONTEXT; 
struct ___CONTEXT_struct {
  unsigned long code; 
  _____CONTEXT *back; 
};
_____CONTEXT *top_context; 


void *table_type[2];

/*==========================*/
/* SOURCE LINE REFERENCE    */
/*==========================*/


/*==========================*/
/* GLOBAL                   */
/*==========================*/

__li__BB li__BB_;
#define li__BB__ (&li__BB_)

__li__AB li__AB_;
#define li__AB__ (&li__AB_)


/*==========================*/
/* STRING CONSTANT          */
/*==========================*/

__li__AB __string_1={11,"hello world\n"};
__li__AB __string_2={26,"Require assertion violated."};

/*==========================*/
/* FUNCTION HEADER          */
/*==========================*/

/* Debug Manager */
void interrupt_signal(int sig);
void lisaac_stack_print(long);        
void print_integer_h(unsigned long n);
void print_integer(long n);           
void lisaac_push_first(_____CONTEXT *path,unsigned long code); 
void lisaac_push(_____CONTEXT *path,unsigned long code);       
/* Source code */
void die_with_code(__li__I li__CG);
void print_char(__li__JB li__3E);
static void li__TG(__li__AB *li__VG);
static __li__C li__BM(__li__I li__DM,__li__I li__EM);
static __li__C li__VM(__li__I li__XM,__li__I li__YM);

/*==========================*/
/* SOURCE CODE              */
/*==========================*/

int main(int argc,char **argv)
{
   __li__I li__DL;
  _____CONTEXT li__QE,li__AL,li__PM,li__UN;
 lisaac_push_first(&li__QE,0); /* L3 STARTUP*/;
  signal(SIGINT,interrupt_signal);
  arg_count  = argc;
  arg_vector = argv;
;
  {
    lisaac_push(&li__QE,1); /* L26 ABSTRACT_STRING*/;
    lisaac_push_first(&li__AL,1); /* L26 ABSTRACT_STRING*/;
    lisaac_push_first(&li__PM,2); /* L64 NUMERIC*/;
    lisaac_push_first(&li__UN,3); /* L50 NUMERIC*/;
    li__DL=(__li__I)(-  1);
    lisaac_push(&li__QE,4); /* L26 ABSTRACT_STRING*/;
    ((__li__BB *)li__BB__)->li__GG=li__DL;
    lisaac_push(&li__QE,5); /* L17 ABSTRACT_STRING*/;
    lisaac_push(&li__QE,6); /* L9 STRING_CONSTANT*/;
    (*li__AB__)=(*li__BB__);
    lisaac_push(&li__QE,7); /* L24 ABSTRACT_STRING*/;
  };
  lisaac_push(&li__QE,8); /* L7 STARTUP*/;
  lisaac_push_first(&li__AL,8); /* L7 STARTUP*/;
  lisaac_push(&li__AL,9); /* L10 STARTUP*/;
  li__TG((&__string_1));
  return 0; /* External alive code */;
  print_char('\0');
  die_with_code( 0);
  return(0);
}


void die_with_code(__li__I li__CG)
/* (Expanded INTEGER{li__I}) Void No recursive, No inlinable. NO CONTEXT! */
{
   _____CONTEXT li__AG;
 lisaac_push_first(&li__AG,10); /* L58 SYSTEM_IO*/;
  exit((li__CG));
}

void print_char(__li__JB li__3E)
/* (Expanded CHARACTER{li__JB}) Void No recursive, No inlinable. NO CONTEXT! */
{
   _____CONTEXT li__1E,li__OG,li__3F;
 lisaac_push_first(&li__1E,11); /* L55 SYSTEM_IO*/;
  lisaac_push_first(&li__OG,12); /* L30 FALSE*/;
  lisaac_push_first(&li__3F,13); /* L53 SYSTEM_IO*/;
  fputc((int)(li__3E),stdout);
}

static void li__TG(__li__AB *li__VG)
/* (Strict STRING_CONSTANT{li__AB}) Void Recursive, No inlinable. NO CONTEXT! */
{
   __li__I li__1I,li__PL,li__UU,li__21,li__VU;
  _____CONTEXT li__UG,li__EI,li__GJ,li__CO,li__OJ,li__M1,li__ZP,li__UQ;
  _____CONTEXT li__HS,li__2Q,li__AQ,li__GU,li__RU,li__Z1,li__01,li__11;
  __li__C li__JJ,li__SL,li__XQ,li__3U,li__EV,li__HV;
  __li__JB *li__FQ,*li__OR;
  __li__JB li__CJ;
 lisaac_push_first(&li__UG,14); /* L1257 ABSTRACT_STRING*/;
  lisaac_push_first(&li__EI,15); /* L22 OUTPUT_STREAM*/;
  lisaac_push_first(&li__GJ,16); /* L123 BLOCK*/;
  li__JJ=li__BM( 15, 10);
  if (li__JJ) {
    lisaac_push(&li__GJ,17); /* L123 BLOCK*/;
    lisaac_push_first(&li__CO,18); /* L50 TRUE*/;
    lisaac_push_first(&li__OJ,19); /* L123 BLOCK*/;
    lisaac_push_first(&li__M1,20); /* L72 TRUE*/;
  } else /* FALSE */ {
    lisaac_push(&li__GJ,17); /* L123 BLOCK*/;
    lisaac_push_first(&li__CO,21); /* L65 FALSE*/;
  };
  lisaac_push(&li__GJ,22); /* L125 BLOCK*/;
  lisaac_push(&li__EI,23); /* L23 OUTPUT_STREAM*/;
  lisaac_push_first(&li__GJ,16); /* L123 BLOCK*/;
  li__JJ=li__BM( 15, 10);
  if (li__JJ) {
    lisaac_push(&li__GJ,17); /* L123 BLOCK*/;
    lisaac_push_first(&li__CO,18); /* L50 TRUE*/;
    lisaac_push_first(&li__OJ,19); /* L123 BLOCK*/;
    lisaac_push_first(&li__M1,20); /* L72 TRUE*/;
  } else /* FALSE */ {
    lisaac_push(&li__GJ,17); /* L123 BLOCK*/;
    lisaac_push_first(&li__CO,21); /* L65 FALSE*/;
  };
  lisaac_push(&li__GJ,22); /* L125 BLOCK*/;
  lisaac_push_first(&li__CO,24); /* L38 FALSE*/;
  li__1I=(*(li__VG)).li__GG;
  lisaac_push(&li__EI,25); /* L27 OUTPUT_STREAM*/;
  li__PL= 0;
  lisaac_push_first(&li__GJ,26); /* L146 NUMERIC*/;
  li__NL:
  {
    lisaac_push(&li__GJ,26); /* L146 NUMERIC*/;
    li__SL=li__VM(li__PL,li__1I);
    if (li__SL) {
      lisaac_push(&li__GJ,27); /* L150 NUMERIC*/;
      lisaac_push_first(&li__CO,28); /* L36 TRUE*/;
      lisaac_push_first(&li__OJ,29); /* L148 NUMERIC*/;
      lisaac_push_first(&li__M1,30); /* L26 OUTPUT_STREAM*/;
      lisaac_push_first(&li__ZP,31); /* L39 ABSTRACT_STRING*/;
      lisaac_push_first(&li__UQ,32); /* L139 BLOCK*/;
      li__XQ=li__BM( 15, 5);
      if (li__XQ) {
        lisaac_push(&li__UQ,33); /* L139 BLOCK*/;
        lisaac_push_first(&li__HS,18); /* L50 TRUE*/;
        lisaac_push_first(&li__2Q,34); /* L139 BLOCK*/;
        lisaac_push_first(&li__AQ,35); /* L39 ABSTRACT_STRING*/;
        lisaac_push_first(&li__GU,36); /* L101 ABSTRACT_STRING*/;
        lisaac_push_first(&li__RU,37); /* L22 ABSTRACT_STRING*/;
        li__UU=(*(li__VG)).li__GG;
        lisaac_push(&li__RU,38); /* L22 ABSTRACT_STRING*/;
        lisaac_push_first(&li__Z1,39); /* L56 NUMERIC*/;
        lisaac_push_first(&li__01,2); /* L64 NUMERIC*/;
        lisaac_push_first(&li__11,3); /* L50 NUMERIC*/;
        li__21=(__li__I)(-  1);
        lisaac_push(&li__Z1,40); /* L56 NUMERIC*/;
        lisaac_push_first(&li__01,3); /* L50 NUMERIC*/;
        li__VU=(__li__I)(li__UU - li__21);
        lisaac_push(&li__GU,41); /* L101 ABSTRACT_STRING*/;
        lisaac_push_first(&li__RU,42); /* L28 NUMERIC*/;
        li__3U=li__VM( 0,li__PL);
        if (li__3U) {
          lisaac_push(&li__RU,43); /* L28 NUMERIC*/;
          lisaac_push_first(&li__Z1,18); /* L50 TRUE*/;
          lisaac_push_first(&li__01,44); /* L28 NUMERIC*/;
          li__EV=li__BM(li__VU,li__PL);
          li__HV=li__EV;
        } else /* FALSE */ {
          lisaac_push(&li__RU,43); /* L28 NUMERIC*/;
          lisaac_push_first(&li__Z1,21); /* L65 FALSE*/;
          li__HV=li__G__;
        };
        if (li__HV) {
          lisaac_push(&li__2Q,45); /* L139 BLOCK*/;
          lisaac_push_first(&li__AQ,20); /* L72 TRUE*/;
          li__EV=li__G__;
        } else /* FALSE */ {
          lisaac_push(&li__2Q,45); /* L139 BLOCK*/;
          lisaac_push_first(&li__AQ,46); /* L87 FALSE*/;
          li__EV=li__B__;
        };
        li__3U=li__EV;
      } else /* FALSE */ {
        lisaac_push(&li__UQ,33); /* L139 BLOCK*/;
        lisaac_push_first(&li__HS,21); /* L65 FALSE*/;
        li__3U=li__G__;
      };
      if (li__3U) {
        lisaac_push(&li__UQ,47); /* L141 BLOCK*/;
        lisaac_push_first(&li__HS,28); /* L36 TRUE*/;
        lisaac_push_first(&li__2Q,48); /* L139 BLOCK*/;
        lisaac_push(&li__2Q,49); /* L140 BLOCK*/;
        lisaac_push_first(&li__AQ,50); /* L46 OBJECT*/;
        lisaac_push_first(&li__GU,51); /* L37 OBJECT*/;
        lisaac_push_first(&li__RU,28); /* L36 TRUE*/;
        lisaac_push_first(&li__Z1,52); /* L35 OBJECT*/;
        lisaac_stack_print(( 7));
        lisaac_push(&li__AQ,53); /* L47 OBJECT*/;
        li__TG((&__string_2));
        lisaac_push(&li__AQ,54); /* L48 OBJECT*/;
        lisaac_push_first(&li__GU,55); /* L58 CHARACTER*/;
        lisaac_push_first(&li__RU,56); /* L18 STD_OUTPUT*/;
        lisaac_push_first(&li__Z1,57); /* L119 OUTPUT_STREAM*/;
        print_char('\n');
        lisaac_push(&li__AQ,58); /* L49 OBJECT*/;
        lisaac_push_first(&li__GU,59); /* L57 OBJECT*/;
        lisaac_push_first(&li__RU,60); /* L49 SYSTEM*/;
        exit(( 1));
      } else /* FALSE */ {
        lisaac_push(&li__UQ,47); /* L141 BLOCK*/;
        lisaac_push_first(&li__HS,24); /* L38 FALSE*/;
      };
      li__FQ=(*(li__VG)).li__HG;
      lisaac_push(&li__ZP,61); /* L43 ABSTRACT_STRING*/;
      li__OR=((__li__JB *)li__FQ);
      lisaac_push_first(&li__UQ,62); /* L107 NATIVE_ARRAY*/;
      lisaac_push_first(&li__HS,32); /* L139 BLOCK*/;
      li__XQ=li__BM( 15, 5);
      if (li__XQ) {
        lisaac_push(&li__HS,33); /* L139 BLOCK*/;
        lisaac_push_first(&li__2Q,18); /* L50 TRUE*/;
        lisaac_push_first(&li__AQ,34); /* L139 BLOCK*/;
        lisaac_push_first(&li__GU,63); /* L107 NATIVE_ARRAY*/;
        li__3U=li__BM(li__PL, 0);
        if (li__3U) {
          lisaac_push(&li__AQ,45); /* L139 BLOCK*/;
          lisaac_push_first(&li__GU,20); /* L72 TRUE*/;
          li__EV=li__G__;
        } else /* FALSE */ {
          lisaac_push(&li__AQ,45); /* L139 BLOCK*/;
          lisaac_push_first(&li__GU,46); /* L87 FALSE*/;
          li__EV=li__B__;
        };
        li__3U=li__EV;
      } else /* FALSE */ {
        lisaac_push(&li__HS,33); /* L139 BLOCK*/;
        lisaac_push_first(&li__2Q,21); /* L65 FALSE*/;
        li__3U=li__G__;
      };
      if (li__3U) {
        lisaac_push(&li__HS,47); /* L141 BLOCK*/;
        lisaac_push_first(&li__2Q,28); /* L36 TRUE*/;
        lisaac_push_first(&li__AQ,48); /* L139 BLOCK*/;
        lisaac_push(&li__AQ,49); /* L140 BLOCK*/;
        lisaac_push_first(&li__GU,50); /* L46 OBJECT*/;
        lisaac_push_first(&li__RU,51); /* L37 OBJECT*/;
        lisaac_push_first(&li__Z1,28); /* L36 TRUE*/;
        lisaac_push_first(&li__01,52); /* L35 OBJECT*/;
        lisaac_stack_print(( 7));
        lisaac_push(&li__GU,53); /* L47 OBJECT*/;
        li__TG((&__string_2));
        lisaac_push(&li__GU,54); /* L48 OBJECT*/;
        lisaac_push_first(&li__RU,55); /* L58 CHARACTER*/;
        lisaac_push_first(&li__Z1,56); /* L18 STD_OUTPUT*/;
        lisaac_push_first(&li__01,57); /* L119 OUTPUT_STREAM*/;
        print_char('\n');
        lisaac_push(&li__GU,58); /* L49 OBJECT*/;
        lisaac_push_first(&li__RU,59); /* L57 OBJECT*/;
        lisaac_push_first(&li__Z1,60); /* L49 SYSTEM*/;
        exit(( 1));
      } else /* FALSE */ {
        lisaac_push(&li__HS,47); /* L141 BLOCK*/;
        lisaac_push_first(&li__2Q,24); /* L38 FALSE*/;
      };
      li__CJ=li__OR[li__PL];
      lisaac_push(&li__M1,64); /* L26 OUTPUT_STREAM*/;
      lisaac_push_first(&li__ZP,56); /* L18 STD_OUTPUT*/;
      lisaac_push_first(&li__UQ,57); /* L119 OUTPUT_STREAM*/;
      print_char(li__CJ);
      lisaac_push(&li__OJ,65); /* L149 NUMERIC*/;
      lisaac_push_first(&li__M1,39); /* L56 NUMERIC*/;
      lisaac_push_first(&li__ZP,2); /* L64 NUMERIC*/;
      lisaac_push_first(&li__UQ,3); /* L50 NUMERIC*/;
      li__UU=(__li__I)(-  1);
      lisaac_push(&li__M1,40); /* L56 NUMERIC*/;
      lisaac_push_first(&li__ZP,3); /* L50 NUMERIC*/;
      li__21=(__li__I)(li__PL - li__UU);
      lisaac_push(&li__OJ,66); /* L149 NUMERIC*/;
      li__PL=li__21;
      goto li__NL;
    } else /* FALSE */ {
      lisaac_push(&li__GJ,27); /* L150 NUMERIC*/;
      lisaac_push_first(&li__CO,24); /* L38 FALSE*/;
    };
  };
}

static __li__C li__BM(__li__I li__DM,__li__I li__EM)
/* (Expanded INTEGER{li__I},Expanded INTEGER{li__I}) With result No recursive, No inlinable. NO CONTEXT! */
{
   _____CONTEXT li__CM,li__Q1;
  __li__C li__GM,li__IM,li__JM,li__FM;
 lisaac_push_first(&li__CM,67); /* L98 NUMERIC*/;
  lisaac_push_first(&li__Q1,68); /* L92 NUMERIC*/;
  li__GM=(li__DM > li__EM);
  li__IM=(li__DM == li__EM);
  if (li__GM) {
    lisaac_push(&li__CM,69); /* L98 NUMERIC*/;
    lisaac_push_first(&li__Q1,70); /* L52 TRUE*/;
    li__JM=li__B__;
  } else /* FALSE */ {
    lisaac_push(&li__CM,69); /* L98 NUMERIC*/;
    lisaac_push_first(&li__Q1,71); /* L67 FALSE*/;
    li__JM=li__IM;
  };
  li__FM=li__JM;
  return(li__FM);
}

static __li__C li__VM(__li__I li__XM,__li__I li__YM)
/* (Expanded INTEGER{li__I},Expanded INTEGER{li__I}) With result No recursive, No inlinable. NO CONTEXT! */
{
   _____CONTEXT li__WM,li__5M;
  __li__C li__2M,li__ZM;
 lisaac_push_first(&li__WM,72); /* L96 NUMERIC*/;
  lisaac_push_first(&li__5M,68); /* L92 NUMERIC*/;
  if ((li__XM > li__YM)) {
    lisaac_push(&li__WM,73); /* L96 NUMERIC*/;
    lisaac_push_first(&li__5M,20); /* L72 TRUE*/;
    li__2M=li__G__;
  } else /* FALSE */ {
    lisaac_push(&li__WM,73); /* L96 NUMERIC*/;
    lisaac_push_first(&li__5M,46); /* L87 FALSE*/;
    li__2M=li__B__;
  };
  li__ZM=li__2M;
  return(li__ZM);
}

/*==========================*/
/* DEBUG MANAGER            */
/*==========================*/

int print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
  return(0);
}

char *trace[50]={
  "./../../make.lip (...)",
  "/home/ben/svn-caca/lisaac/make.lip (.../make.lip)",
  "TRUE (.../lib/base/boolean/true.li)",
  "BOOLEAN (.../lib/base/boolean/boolean.li)",
  "OBJECT (.../lib/base/kernel/object.li)",
  "FALSE (.../lib/base/boolean/false.li)",
  "INTEGER (.../lib/base/number/integer/integer.li)",
  "NUMERIC (.../lib/base/number/low_level/numeric.li)",
  "REAL_32 (.../lib/base/number/real/real_32.li)",
  "FLOAT_MAP32 (.../lib/base/number/low_level/float_map32.li)",
  "FLOAT_MAP (.../lib/base/number/low_level/float_map.li)",
  "UINTEGER_32 (.../lib/base/number/integer/uinteger_32.li)",
  "UNSIGNED_INTEGER (.../lib/base/number/low_level/unsigned_integer.li)",
  "FLOAT_REAL (.../lib/base/number/low_level/float_real.li)",
  "REAL (.../lib/base/number/real/real.li)",
  "INTEGER_32 (.../lib/base/number/integer/integer_32.li)",
  "SIGNED_INTEGER (.../lib/base/number/low_level/signed_integer.li)",
  "STRING_CONSTANT (.../lib/base/string/string_constant.li)",
  "ABSTRACT_STRING (.../lib/base/string/abstract_string.li)",
  "HASHABLE (.../lib/base/property/hashable.li)",
  "COMPARABLE (.../lib/base/property/comparable.li)",
  "CHARACTER (.../lib/base/string/character.li)",
  "CHARACTER_REF (.../lib/base/string/low_level/character_ref.li)",
  "BLOCK (.../lib/base/kernel/block.li)",
  "POINTER (.../lib/base/kernel/pointer.li)",
  "NATIVE_ARRAY (.../lib/base/collection/low_level/native_array.li)",
  "SAFE_EQUAL (.../lib/base/property/safe_equal.li)",
  "STARTUP (.../example/shootout/startup/startup.li)",
  "SYSTEM_IO (.../lib/base/io/low_level/system_io.li)",
  "G_OUT (.../lib/extra/gui/g_out.li)",
  "AREA (.../lib/extra/gui/clipping/area.li)",
  "VIDEO (.../lib/extra/graphics/TARGET/unix/video.li)",
  "PIXEL_24 (.../lib/extra/graphics/pixel_24.li)",
  "PIXEL (.../lib/extra/graphics/low_level/pixel.li)",
  "UINTEGER_8 (.../lib/base/number/integer/uinteger_8.li)",
  "BITMAP (.../lib/extra/graphics/bitmap.li)",
  "ABSTRACT_BITMAP (.../lib/extra/graphics/low_level/abstract_bitmap.li)",
  "INBOX (.../lib/extra/gui/low_level/inbox.li)",
  "G_EXPR (.../lib/extra/gui/low_level/g_expr.li)",
  "G_WIN_IN (.../lib/extra/gui/g_win_in.li)",
  "G_WIN_IN_INTERN (.../lib/extra/gui/low_level/g_win_in_intern.li)",
  "G_GROUP (.../lib/extra/gui/low_level/g_group.li)",
  "STRING (.../lib/base/string/string.li)",
  "ARRAYED (.../lib/base/collection/low_level/arrayed.li)",
  "IO (.../lib/base/io/io.li)",
  "STD_INPUT (.../lib/base/io/std_input.li)",
  "INPUT_STREAM (.../lib/base/io/low_level/input_stream.li)",
  "STD_OUTPUT (.../lib/base/io/std_output.li)",
  "OUTPUT_STREAM (.../lib/base/io/low_level/output_stream.li)",
  "SYSTEM (.../lib/base/system/system.li)"
};

struct __source {
  unsigned int pos;
  char *line;
} __src[74]={
  {397339,"  + name  := STARTUP;"},
  {3419154,"  + upper:INTEGER := -1;"},
  {8408071,"  - '-' Self:SELF :SELF <- SELF.zero - Self;"},
  {6573575,"  - Self:SELF '-'  Left 80  other:SELF :SELF <- `3`;"},
  {3412498,"  + upper:INTEGER := -1;"},
  {2233874,"  + storage:NATIVE_ARRAY(CHARACTER);"},
  {1193489,"  + inherit_abstract_string:Expanded ABSTRACT_STRING;"},
  {3150354,"  - lower:INTEGER; // Always 0"},
  {922139,"  - main <-"},
  {1323547,"    \"hello world\\n\".print;"},
  {7618076,"  - die_with_code code:INTEGER <-"},
  {7211548,"    };"},
  {3942917,"    false_block.value;"},
  {6952988,"    } else {"},
  {164768786,"    IO.put_string Self;"},
  {2886192,"  ( ? {is_connected};"},
  {16132119,"    ((debug_level >=10) && {! value}).if {"},
  {16135191,"    ((debug_level >=10) && {! value}).if {"},
  {6589442,"  - Self:SELF '&&'  Left 20  other:{BOOLEAN}   :BOOLEAN <- other.value;  // and then"},
  {16136727,"    ((debug_level >=10) && {! value}).if {"},
  {9446402,"  - '!' Self:SELF :BOOLEAN <- FALSE;"},
  {8542213,"  - Self:SELF '&&'  Left 20  other:{BOOLEAN}   :BOOLEAN <- FALSE;"},
  {16386583,"    };"},
  {3017264,"    ? {s!=NULL};"},
  {4991493,"  - if true_block:{} :BOOLEAN <- FALSE;"},
  {3541552,"    };"},
  {19142663,"    (Self <= limit_up).if"},
  {19663367,"    };"},
  {4728834,"    true_block.value;"},
  {19408903,"      blc.value Self;"},
  {3422768,"      put_character (s.item i);"},
  {5114898,"    -? {valid_index index};"},
  {18229271,"    ((debug_level >= 5) && {! value}).if {"},
  {18232343,"    ((debug_level >= 5) && {! value}).if {"},
  {18236951,"    ((debug_level >= 5) && {! value}).if {"},
  {5124626,"    -? {valid_index index};"},
  {13255186,"  ( index.in_range lower to count );"},
  {2888210,"  - count:INTEGER <- upper + 1;"},
  {2897938,"  - count:INTEGER <- upper + 1;"},
  {7368711,"  - Self:SELF '+'  Left 80  other:SELF :SELF <- Self - -other;"},
  {7367687,"  - Self:SELF '+'  Left 80  other:SELF :SELF <- Self - -other;"},
  {13255698,"  ( index.in_range lower to count );"},
  {3674631,"  (low <= Self) && {up >= Self};"},
  {3679239,"  (low <= Self) && {up >= Self};"},
  {3682823,"  (low <= Self) && {up >= Self};"},
  {18233879,"    ((debug_level >= 5) && {! value}).if {"},
  {11412485,"  - '!' Self:SELF :BOOLEAN <- TRUE;"},
  {18483735,"    };"},
  {18240535,"    ((debug_level >= 5) && {! value}).if {"},
  {18381847,"      crash_with_message \"Require assertion violated.\" after 7;"},
  {6046724,"    print_runtime_stack_after step;"},
  {4852228,"    };"},
  {4601348,"    (debug_level != 0).if {"},
  {6167044,"    msg.print;"},
  {6298628,"    '\\n'.print;"},
  {7619605,"  - print <- IO.put_character Self;"},
  {2383919,"  - put_character c:CHARACTER <- basic_io_putc c;"},
  {15625776,"  - basic_io_putc c:CHARACTER <- SYSTEM_IO.print_char c;"},
  {6440452,"    die_with_code exit_failure_code;"},
  {7501828,"  - die_with_code exit_code:INTEGER <- SYSTEM.exit exit_code;"},
  {6433841,"  - exit code:INTEGER <- `exit(@code)`; //SYSTEM_IO.die_with_code code;"},
  {5637138,"  );"},
  {14027801,"    -? {index >= 0};"},
  {14032921,"    -? {index >= 0};"},
  {3423280,"      put_character (s.item i);"},
  {19536391,"      (Self + 1).to limit_up do blc;"},
  {19547655,"      (Self + 1).to limit_up do blc;"},
  {12875271,"  - Self:SELF '>='  Right 60 other:SELF :BOOLEAN <- (Self > other) | (Self = other);"},
  {12079111,"  - Self:SELF '>'   Right 60 other:SELF :BOOLEAN <- `2`;"},
  {12879879,"  - Self:SELF '>='  Right 60 other:SELF :BOOLEAN <- (Self > other) | (Self = other);"},
  {6837762,"  - Self:SELF '|'   Left 10  other:BOOLEAN :BOOLEAN <- TRUE;  // or"},
  {8803845,"  - Self:SELF '|'   Left 10  other:BOOLEAN :BOOLEAN <- other;"},
  {12614151,"  - Self:SELF '<='  Right 60 other:SELF :BOOLEAN <- ! (Self > other);"},
  {12610055,"  - Self:SELF '<='  Right 60 other:SELF :BOOLEAN <- ! (Self > other);"}
};

/* Unix Signal manager: */
void interrupt_signal(int sig)  
{                               
  lisaac_stack_print(0);     
  print_string("User interrupt.\n"); 
  die_with_code(1);                     
}                                       

void lisaac_push_first(_____CONTEXT *path,unsigned long code)
{ 
  path->back  = top_context;
  path->code  = code;
  top_context = path;
} 
  
void lisaac_push(_____CONTEXT *path,unsigned long code)
{ 
  path->code  = code;
  top_context = path;
} 
  
  
void lisaac_stack_print(long step)           
{ _____CONTEXT *back,*next,*up;              
  int j;	                              
  up = top_context;                          
  for (j=0;j<step;j++) up = up->back;        
  next = (void *)0;                          
  while (up != (void *)0) {                  
    back = up -> back;                       
    up -> back = next;                       
    next = up;                               
    up = back;                               
  };                                         
  print_string("\n============== BOTTOM ==============\n"); 
  while (next != (void *)0) {                
    print_string("Line #");                           
    print_integer(__src[next->code].pos >> 17);         
    print_string(" Column #");                        
    print_integer((__src[next->code].pos >> 9) & 0xFF); 
    print_string(" in ");                             
    print_string(trace[__src[next->code].pos & 0x1FF]); 
    print_string(".\n");                             
    print_string(__src[next->code].line);               
    print_char('\n');                                  
    for (j=0;j < ((__src[next->code].pos >> 9) & 0xFF);j++) {
      if (__src[next->code].line[j]=='\t') print_char('\t');
      else print_char(' ');
    };                                                  
    print_char('^');                                    
    print_char('\n');                                  
    next = next -> back;                     
  };                                         
  print_string("================ TOP ===============\n"); 
  top_context = (void *)0;                   
}                                            
 
void print_integer(long n)           
{ long val;                          
  char car;                          
  if (n<0) { print_char('-'); n=-n;};
  car = (n % 10) + '0';              
  val = n / 10;                      
  if (val != 0) print_integer(val);  
  print_char(car);                   
} 

void print_integer_h_2(unsigned long n,long l) 
{ unsigned long val,v,j;            
  char car;                           
  v = n & 0xF;                        
  if (v < 10) car = v + '0'; else car = (v-10) + 'A'; 
  val = n >> 4;                       
  if (val != 0) print_integer_h_2(val,l-1); else 
  for (j=0;j<l;j++) print_string("-"); 
  print_char(car);                    
} 
 
void print_integer_h(unsigned long n)  
{                                      
  print_integer_h_2(n,15);             
} 
 

