name: Sync from external ZIP

on:
  schedule:
    - cron: "0 6 * * *"   # tous les jours à 6h UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Download external ZIP
        run: curl -L -o lisaac_0.5.zip https://lisaac.org/downloads/lisaac_0.5.zip

      - name: Unzip lisaac content
        run: |
          unzip -o lisaac_0.5.zip
          rsync -av lisaac/ ./
          rm -rf lisaac lisaac_0.5.zip

      - name: Sync files (commit)
        run: |
          git config user.name "Lisaac Bot"
          git config user.email "github-bot@lisaac.org"
          git checkout main
          git add -A
          if git diff --cached --quiet; then
            echo "Aucun changement"
          else
            git commit -m "Synchronisation avec le ZIP officiel
            Co-authored-by: Dominique Colnet <dominique.colnet@loria.fr>
            Co-authored-by: Benoit Sonntag <benoit.sonntag@lisaac.org>"
          fi

      - name: Push
        run: git push https://x-access-token:${{ secrets.PAT }}@github.com/lisaac-omega/lisaac.git main